### ISSUE TITLE
MissingMethod SendFileAsync

### ISSUE THREAD

**Issue by Yucked** [RogueException/Discord.Net#1068]
After updating to the latest Discord.Net nightly build, this exception is thrown as soon as you run the bot. The program builds fine without throwing any errors. I'm not using `SendFileAsync` anywhere in my bot. 
```System.MissingMethodException
  HResult=0x80131513
  Message=Method not found: 'System.Threading.Tasks.Task`1<Discord.IUserMessage> Discord.IMessageChannel.SendFileAsync(System.String, System.String, Boolean, Discord.Embed, Discord.RequestOptions)'.
  Source=Discord.Net.WebSocket
  StackTrace:
   at Discord.WebSocket.ClientState..ctor(Int32 guildCount, Int32 dmChannelCount)
   at Discord.WebSocket.DiscordSocketClient..ctor(DiscordSocketConfig config, DiscordSocketApiClient client, SemaphoreSlim groupLock, DiscordSocketClient parentClient)
   at Discord.WebSocket.DiscordSocketClient..ctor(DiscordSocketConfig config)
   at Valerie.Core.<InitializeAsync>d__1.MoveNext() in G:\Github projects\Valerie\Core.cs:line 20
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Valerie.Core.Main(String[] args) in G:\Github projects\Valerie\Core.cs:line 17```

**Comment by Joe4evr** [comment]
It looks like for some reason, that particular method is [only conditionally included](https://github.com/RogueException/Discord.Net/blob/dev/src/Discord.Net.Core/Entities/Channels/IMessageChannel.cs#L12-L15).

**Comment by Hawxy** [comment]
#1046 should fix this, as the constants have been removed.

**Comment by Yucked** [comment]
Closing it since #1046 fixed it.
