### ISSUE TITLE
IAudioClient "System.MissingMethodException"

### ISSUE THREAD

**Issue by ComputerMaster1st** [RogueException/Discord.Net#1092]
Hi There,

This is triggered on dev build 00969 when connecting to gateway. OS this is being debugged on is Ubuntu 16.04 & is targeting netcore 2.1. Previous build used was 00957 which is fine. Reason for updating to latest build was to see if anything was new.

```
13:16:37 Hidden Ex    Detected Hidden Exception!:
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (WebSocket connection was closed) ---> System.Exception: WebSocket connection was closed ---> System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<Discord.Audio.IAudioClient> Discord.IAudioChannel.ConnectAsync(System.Action`1<Discord.Audio.IAudioClient>)'.
   at Discord.WebSocket.DiscordSocketClient.ProcessMessageAsync(GatewayOpCode opCode, Nullable`1 seq, String type, Object payload)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Discord.WebSocket.DiscordSocketClient.ProcessMessageAsync(GatewayOpCode opCode, Nullable`1 seq, String type, Object payload)
   at Discord.EventExtensions.InvokeAsync[T1,T2,T3,T4](AsyncEvent`1 eventHandler, T1 arg1, T2 arg2, T3 arg3, T4 arg4)
   at Discord.API.DiscordSocketApiClient.<.ctor>b__24_0(Byte[] data, Int32 index, Int32 count)
   at Discord.Net.WebSockets.DefaultWebSocketClient.RunAsync(CancellationToken cancelToken)
   --- End of inner exception stack trace ---
   at Discord.ConnectionManager.WaitAsync()
   at Discord.WebSocket.DiscordSocketClient.OnConnectingAsync()
   at Discord.WebSocket.DiscordSocketClient.OnConnectingAsync()
   at Discord.ConnectionManager.ConnectAsync(CancellationTokenSource reconnectCancelToken)
   at Discord.ConnectionManager.<>c__DisplayClass28_0.<<StartAsync>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Exception: WebSocket connection was closed ---> System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<Discord.Audio.IAudioClient> Discord.IAudioChannel.ConnectAsync(System.Action`1<Discord.Audio.IAudioClient>)'.
   at Discord.WebSocket.DiscordSocketClient.ProcessMessageAsync(GatewayOpCode opCode, Nullable`1 seq, String type, Object payload)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Discord.WebSocket.DiscordSocketClient.ProcessMessageAsync(GatewayOpCode opCode, Nullable`1 seq, String type, Object payload)
   at Discord.EventExtensions.InvokeAsync[T1,T2,T3,T4](AsyncEvent`1 eventHandler, T1 arg1, T2 arg2, T3 arg3, T4 arg4)
   at Discord.API.DiscordSocketApiClient.<.ctor>b__24_0(Byte[] data, Int32 index, Int32 count)
   at Discord.Net.WebSockets.DefaultWebSocketClient.RunAsync(CancellationToken cancelToken)
   --- End of inner exception stack trace ---
   at Discord.ConnectionManager.WaitAsync()
   at Discord.WebSocket.DiscordSocketClient.OnConnectingAsync()
   at Discord.WebSocket.DiscordSocketClient.OnConnectingAsync()
   at Discord.ConnectionManager.ConnectAsync(CancellationTokenSource reconnectCancelToken)
   at Discord.ConnectionManager.<>c__DisplayClass28_0.<<StartAsync>b__0>d.MoveNext()<---
```

This is all I can provide.

**Comment by FiniteReality** [comment]
Looks like you didn't update properly, we removed the overload for ConnectAsync which takes an action.

**Comment by ComputerMaster1st** [comment]
Just updating the myget version should work yes?

**Comment by FiniteReality** [comment]
It should do.

**Comment by ComputerMaster1st** [comment]
Just performed restore and same exception. `dotnet build` produces no errors.

**Comment by FiniteReality** [comment]
Do you have anything listening to UserVoiceStateUpdated/VoiceServerUpdated event?

**Comment by ComputerMaster1st** [comment]
UserVoiceStateUpdated for Music Auto-Join functionality. Does not execute unless a user is detected going into a voice channel.

**Comment by FiniteReality** [comment]
What's the code? You're calling an overload which should not exist, so maybe you should try recompiling your code.

**Comment by ComputerMaster1st** [comment]
```
        private async Task UserVoiceUpdatedAsync(SocketUser sUser, SocketVoiceState before, SocketVoiceState after) {
            if (sUser.IsBot || sUser.IsWebhook) return;

            IGuildUser user = (IGuildUser)sUser;
            IGuild guild = user.Guild;

            if (playerManager.IsCreated(guild.Id) || user.VoiceChannel == null) 
                return;

            GD_Music gMusic = await vgMusic.GetAsync(guild.Id);

            if (gMusic == null) return;

            IVoiceChannel vc = user.VoiceChannel;
            ITextChannel tc = (gMusic.AutoTextChannel != 0) ? await guild.GetTextChannelAsync(gMusic.AutoTextChannel) : null;

            if (vc.Id == gMusic.AutoVoiceChannel && tc != null)
                await playerManager.CreatePlayerAsync(user, vc, tc, true);
        }
```

**Comment by FiniteReality** [comment]
And the source for CreatePlayerAsync? I'm guessing somewhere you're calling ConnectAsync() and didn't make sure it was compiled against the latest version so it ended up calling an overload which no longer exists.

**Comment by ComputerMaster1st** [comment]
```
        private async Task ConnectToVoiceAsync()
            => client = await VoiceChannel.ConnectAsync();
```

This is the only connectasync line.

**Comment by FiniteReality** [comment]
Yeah, recompile your code and it should work.

**Comment by ComputerMaster1st** [comment]
That's a no-go. Performed `dotnet clean` & `dotnet build` and same issue.

**Comment by FiniteReality** [comment]
Try deleting your `project.assets.json` (it's in the obj folder for the project) and re-restore, and rebuild. It appears like it's running against the latest version, while it compiles against an older version.

**Comment by Joe4evr** [comment]
In the most extreme case, you may want to do the follwing: While VS is closed, delete the project's `bin` and `obj` entirely, then go to `Users\%USERNAME%\.nuget` and delete (some/all) of the Discord.Net packages you have there.

**Comment by ComputerMaster1st** [comment]
Followed both cases and both failed. However, I did notice that upon restoring after deleting all data from .nuget, it begun downloading 00957. Only the WS4Net downloaded as 00969.

```
computermaster1st@computermaster1st-laptop:~/Github/Railgun$ dotnet restore
  Restoring packages for /home/computermaster1st/Github/Railgun/Railgun/Railgun.csproj...
  Restore completed in 123.74 ms for /home/computermaster1st/Github/Railgun/Shared.Music/src/AudioChord.Parsers/AudioChord.Parsers.csproj.
  Restoring packages for /home/computermaster1st/Github/Railgun/Shared.Music/src/AudioChord/AudioChord.csproj...
  Restoring packages for /home/computermaster1st/Github/Railgun/TreeDiagram/TreeDiagram.csproj...
  Installing System.Threading.Overlapped 4.3.0.
  Installing System.Net.NetworkInformation 4.3.0.
  Installing System.Security.Principal 4.0.1.
  Installing System.Security.Claims 4.0.1.
  Installing runtime.native.System.Net.Security 4.0.1.
  Installing System.Threading.ThreadPool 4.0.10.
  Installing System.Threading.Thread 4.0.0.
  Installing Microsoft.Win32.Registry 4.0.0.
  Installing System.Net.WebHeaderCollection 4.0.1.
  Installing System.ComponentModel.Primitives 4.1.0.
  Installing System.ComponentModel 4.0.1.
  Installing DnsClient 1.0.7.
  Installing System.Security.SecureString 4.0.0.
  Installing System.Net.Security 4.0.0.
  Installing System.Diagnostics.TraceSource 4.0.0.
  Installing System.Collections.Specialized 4.0.1.
  Installing System.Net.Requests 4.0.11.
  Installing AngleSharp 0.9.9.1.
  Installing System.Diagnostics.Process 4.1.0.
  Installing YoutubeExplode 4.2.8.
  Installing MongoDB.Driver.GridFS 2.7.0-beta0001.
  Installing MongoDB.Driver 2.7.0-beta0001.
  Installing MongoDB.Bson 2.7.0-beta0001.
  Installing MongoDB.Driver.Core 2.7.0-beta0001.
  Installing System.ComponentModel.TypeConverter 4.1.0.
  Installing System.Collections.NonGeneric 4.0.1.
  Installing Discord.Net 2.0.0-beta2-00957.
  Installing Google.Apis.YouTube.v3 1.34.0.1226.
  Installing Discord.Net.Providers.WS4Net 2.0.0-beta2-00969.
  Installing Discord.Net.Core 2.0.0-beta2-00957.
  Installing Discord.Net.Rest 2.0.0-beta2-00957.
  Installing Discord.Net.WebSocket 2.0.0-beta2-00957.
  Installing Discord.Net.Commands 2.0.0-beta2-00957.
  Installing Discord.Net.Webhook 2.0.0-beta2-00957.
  Installing Google.Apis 1.34.0.
  Installing Google.Apis.Auth 1.34.0.
  Installing Discord.Net.Core 2.0.0-beta2-00969.
  Installing WebSocket4Net 0.15.2.
  Installing System.Collections.Immutable 1.4.0.
  Installing Google.Apis.Core 1.34.0.
  Installing Microsoft.Extensions.DependencyInjection 2.0.0.
  Installing System.Net.Http 4.3.1.
  Installing System.Net.Requests 4.3.0.
  Installing SuperSocket.ClientEngine.Core 0.10.0.
  Installing Microsoft.Extensions.DependencyInjection.Abstractions 2.0.0.
  Installing System.Net.WebHeaderCollection 4.3.0.
  Installing Newtonsoft.Json 10.0.2.
  Restore completed in 5.01 sec for /home/computermaster1st/Github/Railgun/Shared.Music/src/AudioChord/AudioChord.csproj.
  Restore completed in 5.22 sec for /home/computermaster1st/Github/Railgun/Railgun/Railgun.csproj.
  Restore completed in 4.8 sec for /home/computermaster1st/Github/Railgun/TreeDiagram/TreeDiagram.csproj.
computermaster1st@computermaster1st-laptop:~/Github/Railgun$
```

**Comment by ComputerMaster1st** [comment]
My apologies, I figured it out. I've done a Herper McDerpington. Turned out the csproj file didn't have the right build number.

Closing due to no longer a problem.
