### ISSUE TITLE
SocketGuild#GetVanityInviteAsync throws a nullref

### ISSUE THREAD

**Issue by QuantumToasted** [RogueException/Discord.Net#1156]
```
System.NullReferenceException: Object reference not set to an instance of an object.
at Discord.Rest.RestInvite.Update(Invite model)
at Discord.Rest.RestInviteMetadata.Update(InviteMetadata model)
at Discord.Rest.RestInviteMetadata.Create(BaseDiscordClient discord, IGuild guild, IChannel channel, InviteMetadata model)
at Discord.Rest.GuildHelper.<GetVanityInviteAsync>d__18.MoveNext()
```

The guild has a valid vanity URL.
I am on nightly `2.0.0-beta2-00991`.

**Comment by Still34** [comment]
#1094 introduced this method, which did not account for the custom return type of the endpoint. Will push a fix later.
