### ISSUE TITLE
"A task was canceled" when invoking LoginAsync()

### ISSUE THREAD

**Issue by whc2001** [RogueException/Discord.Net#1187]
Windows 10, DotNet Core 2.1
```
    public class DiscordManager
    {
        private DiscordSocketClient client;

        public event Func<Task> OnLogin, OnLogout;
        public event Func<LogMessage, Task> OnLog;
        public event Func<SocketMessage, Task> OnMessage;

        public async void Begin(string token)
        {
            client = new DiscordSocketClient();

            client.LoggedIn += Client_LoggedIn;
            client.LoggedOut += Client_LoggedOut;
            client.Log += Client_Log;
            client.MessageReceived += Client_MessageReceived;

            await client.LoginAsync(TokenType.Bot, token, true);
            await client.StartAsync();

        }

        private async Task Client_MessageReceived(SocketMessage arg)
        {
            await Task.Run(() => this.OnMessage?.Invoke(arg));
        }

        private async Task Client_Log(LogMessage arg)
        {
            Debug.Print(arg.Message);
            await Task.Run(() => this.OnLog?.Invoke(arg));
        }

        private async Task Client_LoggedOut()
        {
            await Task.Run(() => this.OnLogout?.Invoke());
        }

        private async Task Client_LoggedIn()
        {
            await Task.Run(() => this.OnLogin?.Invoke());
        }

        public List<SocketGroupChannel> GetChannels()
        {
            return new List<SocketGroupChannel>(client.GroupChannels);
        }
    }
```

```
        static void Main(string[] args)
        {
            discord = new DiscordManager();
            discord.Begin("NTA3MDQ5M...8ZwTATauXrA");
            while (true)
                Thread.Sleep(10);
        }
```

The program won't startup, an exception is thrown at the ` await client.LoginAsync(TokenType.Bot, token, true);` line, says "A task was canceled". No other information.
 
```
System.Threading.Tasks.TaskCanceledException
  HResult=0x8013153B
  Message=A task was canceled.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ToukenBot.DiscordInterface.DiscordManager.<Client_LoggedIn>d__17.MoveNext() in [...]:line 51
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Discord.EventExtensions.<InvokeAsync>d__0.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Rest.BaseDiscordClient.<LoginInternalAsync>d__34.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Rest.BaseDiscordClient.<LoginAsync>d__33.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ToukenBot.DiscordInterface.DiscordManager.<Begin>d__13.MoveNext() in [...]:line 28
```

**Comment by whc2001** [comment]
Solved, cannot use `event?.Invoke();`, must use `if(event != null) event.Invoke();`.

**Comment by Joe4evr** [comment]
![](https://i.kym-cdn.com/entries/icons/original/000/018/489/nick-young-confused-face-300x256-nqlyaa.jpg)

**Comment by whc2001** [comment]
Don't know why, but give up using nullable on events does solve the problem.
