### ISSUE TITLE
Error While Modifying Message

### ISSUE THREAD

**Issue by BillChirico** [RogueException/Discord.Net#1289]
Hello,

I was trying to modify a messages embed and received the following error:

```
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at Discord.API.DiscordRestApiClient.DeserializeJson[T](Stream jsonStream)
   at Discord.API.DiscordRestApiClient.SendJsonAsync[TResponse](String method, String endpoint, Object payload, String bucketId, ClientBucketType clientBucket, RequestOptions options)
   at Discord.API.DiscordRestApiClient.ModifyMessageAsync(UInt64 channelId, UInt64 messageId, ModifyMessageParams args, RequestOptions options)
   at Discord.Rest.MessageHelper.ModifyAsync(IMessage msg, BaseDiscordClient client, Action`1 func, RequestOptions options)
   at Discord.Rest.RestUserMessage.ModifyAsync(Action`1 func, RequestOptions options)
```

**Comment by FiniteReality** [comment]
Looks like an API endpoint returned HTML instead of the expected JSON. It might just be a hiccup in CloudFlare, or you might've been IP banned.

**Comment by BillChirico** [comment]
@FiniteReality I’m not IP banned because it worked after restarting my bot.

**Comment by Chris-Johnston** [comment]
Is there a reason why we don't check the content-type header before deserializing the JSON? I think that might help debug this, even if it's a rare occurrence
