### ISSUE TITLE
NRE when handling Dispatch (MESSAGE_CREATE)

### ISSUE THREAD

**Issue by JustArchi** [RogueException/Discord.Net#1295]
Full log:

```
2019-04-13 11:54:47|ERROR|ArchiBot|OnLog() Gateway | Error handling Dispatch (MESSAGE_CREATE)
2019-04-13 11:54:47|ERROR|ArchiBot|OnLog() System.NullReferenceException: Object reference not set to an instance of an object.
   at Discord.WebSocket.SocketGuild.AddOrUpdateUser(GuildMember model)
   at Discord.WebSocket.DiscordSocketClient.ProcessMessageAsync(GatewayOpCode opCode, Nullable`1 seq, String type, Object payload)

```

I'm not sure how this has happened, I'm unable to reproduce this, it happened on its own a few days after the bot was running properly.

Thank you in advance for taking a look.

**Comment by Anu6is** [comment]
This has been reported previously and should have been resolved with https://github.com/discord-net/Discord.Net/pull/1268. You'd need to use the nightly build in order to benefit from this fix however.

**Comment by JustArchi** [comment]
Sorry for duplicate then, I've searched for `Error handling Dispatch (MESSAGE_CREATE)` but didn't find anything recent.

I'd like to request updating the stable with this fix in near future then, thank you!
