### ISSUE TITLE
AudioClient issues...

### ISSUE THREAD

**Issue by nkrs200** [RogueException/Discord.Net#1449]
I'm not sure what is going on, but ever since late October, whenever my Bot tries to play audio, it always errors out at `using (var discord = AudioClient.CreatePCMStream(AudioApplication.Mixed)` with the following exception:

System.BadImageException

Is there something that I am doing wrong?  I've been using the same code for a year and a half (ever since the migration to 2.x when it first went into prerelease), and it has followed the documentation's example since day one.

Edit:  This happens when it tries to join an audio channel as well.

Edit 2:  Here is a stacktrace of the exception.
   at Discord.Audio.OpusDecoder.CreateDecoder(Int32 Fs, Int32 channels, OpusError& error)
   at Discord.Audio.OpusDecoder..ctor()
   at Discord.Audio.Streams.OpusDecodeStream..ctor(AudioStream next)
   at Discord.Audio.AudioClient.<CreateInputStreamAsync>d__54.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.WebSocket.SocketGuild.<RepopulateAudioStreamsAsync>d__229.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.WebSocket.SocketGuild.<FinishConnectAudio>d__228.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Discord.WebSocket.SocketGuild.<ConnectAudioAsync>d__225.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Discord.WebSocket.SocketGuild.<ConnectAudioAsync>d__225.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.WebSocket.SocketVoiceChannel.<ConnectAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at RadioBot.AudioService.<JoinAudio>d__13.MoveNext() in D:\Documents\Visual Studio 2015\Projects\Radio\Radio Refresh Ver 2\AudioService.cs:line 62

The line is referring to contains this simple line of code:  `await target.ConnectAsync();`

**Comment by FiniteReality** [comment]
`BadImageFormatException` means it tried to load an invalid DLL. Which means that your native dependencies are either missing, are corrupted, or are for a different bitness (32-bit vs 64-bit)

**Comment by Still34** [comment]
This issue appears to be solved. Please re-open the issue if you continue to experience further problems with the audio binaries.
