### ISSUE TITLE
Exception: Error converting value "member" to type 'Discord.PermissionTarget'

### ISSUE THREAD

**Issue by RheaAyase** [RogueException/Discord.Net#1507]
`Guild.GetAuditLogsAsync(n)` seems to sometimes throw:
```
Exception: Error converting value "member" to type 'Discord.PermissionTarget'. Path '[0].type'.
    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
    at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
    at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)
    at Discord.Rest.ChannelCreateAuditLogData.Create(BaseDiscordClient discord, AuditLog log, AuditLogEntry entry)
    at Discord.Rest.AuditLogHelper.CreateData(BaseDiscordClient discord, AuditLog log, AuditLogEntry entry)
    at Discord.Rest.RestAuditLogEntry..ctor(BaseDiscordClient discord, AuditLog fullLog, AuditLogEntry model, IUser user)
    at Discord.Rest.RestAuditLogEntry.Create(BaseDiscordClient discord, AuditLog fullLog, AuditLogEntry model)
    at Discord.Rest.GuildHelper.<>c__DisplayClass27_1.<GetAuditLogsAsync>b__2(AuditLogEntry x)
    at System.Linq.Enumerable.SelectArrayIterator`2.ToArray() in /_/src/System.Linq/src/System/Linq/Select.SpeedOpt.cs:line 80
    at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items) in /_/src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray.cs:line 112
    at Discord.Rest.GuildHelper.<>c__DisplayClass27_0.<<GetAuditLogsAsync>b__0>d.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
    at Discord.PagedAsyncEnumerable`1.Enumerator.MoveNextAsync()

InnerException: Requested value 'member' was not found.
    at Newtonsoft.Json.Utilities.EnumUtils.ParseEnum(Type enumType, NamingStrategy namingStrategy, String value, Boolean disallowNumber)
    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
```

**Comment by NeKzor** [comment]
I can reproduce this by creating and then deleting a user overwrite for a text channel using 2.3.0-dev-20200425.1.

Edit: Actually cannot reproduce the exact bug in ChannelCreateAuditLogData but this seems to be related to #1407.

```
---> Newtonsoft.Json.JsonSerializationException: Error converting value "member" to type 'Discord.PermissionTarget'. Path ''.
---> System.ArgumentException: Requested value 'member' was not found.
    at Newtonsoft.Json.Utilities.EnumUtils.ParseEnum(Type enumType, NamingStrategy namingStrategy, String value, Boolean disallowNumber)
    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
    --- End of inner exception stack trace ---
    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
    at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
    at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
    at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)
    at Discord.Rest.OverwriteDeleteAuditLogData.Create(BaseDiscordClient discord, AuditLog log, AuditLogEntry entry)
    at Discord.Rest.AuditLogHelper.CreateData(BaseDiscordClient discord, AuditLog log, AuditLogEntry entry)
    at Discord.Rest.RestAuditLogEntry..ctor(BaseDiscordClient discord, AuditLog fullLog, AuditLogEntry model, IUser user)
    at Discord.Rest.RestAuditLogEntry.Create(BaseDiscordClient discord, AuditLog fullLog, AuditLogEntry model)
    at Discord.Rest.GuildHelper.<>c__DisplayClass27_1.<GetAuditLogsAsync>b__2(AuditLogEntry x)
    at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
    at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
    at System.Collections.Immutable.ImmutableArray.ToImmutableArray[TSource](IEnumerable`1 items)
    at Discord.Rest.GuildHelper.<>c__DisplayClass27_0.<<GetAuditLogsAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
    at Discord.PagedAsyncEnumerable`1.Enumerator.MoveNextAsync()
    at System.Linq.AsyncEnumerable.SelectManyAsyncIterator`2.ToListAsync(CancellationToken cancellationToken) in d:\a\1\s\Ix.NET\Source\System.Linq.Async\System\Linq\Operators\SelectMany.cs:line 392
    at System.Linq.AsyncEnumerable.SelectManyAsyncIterator`2.ToListAsync(CancellationToken cancellationToken) in d:\a\1\s\Ix.NET\Source\System.Linq.Async\System\Linq\Operators\SelectMany.cs:line 392
    at System.Linq.AsyncEnumerable.SelectManyAsyncIterator`2.ToArrayAsync(CancellationToken cancellationToken) in d:\a\1\s\Ix.NET\Source\System.Linq.Async\System\Linq\Operators\SelectMany.cs:line 383
    at Discord.AsyncEnumerableExtensions.FlattenAsync[T](IAsyncEnumerable`1 source)
    at Discord.WebSocket.SocketGuild.Discord.IGuild.GetAuditLogsAsync(Int32 limit, CacheMode cacheMode, RequestOptions options, Nullable`1 beforeId, Nullable`1 userId, Nullable`1 actionType)
```
