### ISSUE TITLE
Unable to DM users with userID

### ISSUE THREAD

**Issue by ZachSears** [RogueException/Discord.Net#1534]
Hello, I am trying to get the users userID by using message. Doing the following:

```csharp        
        IMessage suggestion = await Context.Channel.GetMessageAsync(msgID);
```

Then DMing the user by the following:
```csharp
await suggestion.Author.SendMessageAsync("Test");
```

With this I am getting the following Exception 

```
Discord.Net.HttpException: The server responded with error 50007: Cannot send messages to this user
   at Discord.Net.Queue.RequestBucket.<SendAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Net.Queue.RequestQueue.<SendAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.API.DiscordRestApiClient.<SendInternalAsync>d__64.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.API.DiscordRestApiClient.<SendJsonAsync>d__61`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.API.DiscordRestApiClient.<CreateDMChannelAsync>d__147.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Rest.UserHelper.<CreateDMChannelAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.WebSocket.SocketUser.<GetOrCreateDMChannelAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.UserExtensions.<SendMessageAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Discord_Bot.Commands.Commands.suggest.<approve>d__3.MoveNext() in C:\Users\zachary\source\repos\Discord Bot\Discord Bot\Main\Commands\Suggestions.cs:line 71
```

Also I do have my DMs open therefore I shouldn't be getting this error.

If you need anymore information to help me please let me know. I am free to share the whole command code as well.

**Comment by IvMisticos** [comment]
Are you sure that you are not using your bot message/ID and etc? Did you debug it to make sure it is the correct user, ...?

**Comment by ZachSears** [comment]
> Are you sure that you are not using your bot message/ID and etc? Did you debug it to make sure it is the correct user, ...?

Thank you I forgot about the fact that you are pulling the bot's userid because that is the user that is sending the embed message to the chat. I have figured it out and coded the needed parts.

**Comment by diogoribeirodev** [comment]
are you able to use this code to dm people of a given server?

**Comment by ZachSears** [comment]
> are you able to use this code to dm people of a given server?

You can use this to DM people but not the exact code that I posted. I have a command that DMs users but I do not know wha you are after or what you are trying to do but this is what I'm doing to DM users 

```
 public async Task dmUser(ulong userid, [Remainder] string message)
        {
            var userMentioned = Context.Guild.GetUser(userid);
            await userMentioned.SendMessageAsync(message);
        }
```

**Comment by diogoribeirodev** [comment]
Thank you this will help me alot!!! I'm gonna try to figure out how to use
the actual API, store the tokens, get the server..., hope i can do it!

A segunda, 12/04/2021, 14:15, Zachary Sears ***@***.***>
escreveu:

**Comment by diogoribeirodev** [comment]
how did you created the variable context? sry if i am doing nooby questions!

**Comment by diogoribeirodev** [comment]
?

**Comment by diogoribeirodev** [comment]
Is this how you do it?
public static void Main(string[] args)
        => new Program().MainAsync().GetAwaiter().GetResult();

        private DiscordSocketClient _client;

        public async Task MainAsync()
        {
            _client = new DiscordSocketClient();
            var token = File.ReadAllText("token.txt");
            await _client.LoginAsync(TokenType.Bot, token);
            await _client.StartAsync();
            await Task.Delay(-1);
        }
        private Task LogAsync(LogMessage log)
        {
            Console.WriteLine(log.ToString());
            return Task.CompletedTask;
        }
        private Task ReadyAsync()
        {
            Console.WriteLine($"{_client.CurrentUser} is connected!");

            return Task.CompletedTask;
        }
        [Command("DM")]
        public async Task DmUser(ulong id, string message)
        {
            message = "pong";
            var dm = _client.GetUser(id);
            await dm.SendMessageAsync(message);
        }

**Comment by ZachSears** [comment]
> Is this how you do it?



I have a starter bot for Discord.NET that I coded I’m not sure what it needs I think it needs the NuGet stuff but no.

 You don’t put commands inside of your program.cs as well as you need to have a commandhandler etc. to use the command and everything.

**Comment by diogoribeirodev** [comment]
i have a command handler

**Comment by diogoribeirodev** [comment]
Fck, i need this by tomorrow and it's so hard!!!

**Comment by ZachSears** [comment]
> Fck, i need this by tomorrow and it's so hard!!!


Upload it to Github and I will edit it to what you need. Add necessary stuff you need/want to it and I will make it for you.

**Comment by diogoribeirodev** [comment]
Hi, here it is, thx for your help!!!!
https://github.com/MoneyMachine555/DiscordBotDM

**Comment by ZachSears** [comment]
> Hi, here it is, thx for you help!!!!
> https://github.com/MoneyMachine555/DiscordBotDM

What is your exact purpose? And what do you need/want it to do just DM someone in a server with their userID or what?

**Comment by diogoribeirodev** [comment]
I just want do dm people in a server.

**Comment by MoneyMachine555** [comment]
Thank you, again for the help! Can I compensate you in any way?

**Comment by MoneyMachine555** [comment]
?

**Comment by MoneyMachine555** [comment]
?

**Comment by diogoribeirodev** [comment]
?

**Comment by diogoribeirodev** [comment]
Thank you, again for the help! Can I compensate you in any way?

**Comment by SubZero0** [comment]
Please, stop  spamming a closed issue. Try contacting them in other way if you want.
