### ISSUE TITLE
AddModulesAsync tries to instantiate the module?

### ISSUE THREAD

**Issue by mooop12** [RogueException/Discord.Net#1547]
I added a database context to the root service provider:
```
services.AddScoped<DatabaseContext>();
```

I'm executing commands in a service scope:
```
using IServiceScope scope = _serviceProvider.CreateScope();
IResult result = await _commands.ExecuteAsync(context, argPos, scope.ServiceProvider);
```

But a call to AddModulesAsync (not in a scope) results in an exception:
```
System.InvalidOperationException: Cannot resolve scoped service 'foo.Persistence.DatabaseContext' from root provider.
  at at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.ValidateResolution(Type serviceType, IServiceScope scope, IServiceScope rootScope)
  at at Microsoft.Extensions.DependencyInjection.ServiceProvider.Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceProviderEngineCallback.OnResolve(Type serviceType, IServiceScope scope)
  at at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
  at at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
  at at Discord.Commands.ReflectionUtils.GetMember(CommandService commands, IServiceProvider services, Type memberType, TypeInfo ownerType)
  at at Discord.Commands.ReflectionUtils.<>c__DisplayClass2_0`1.<CreateBuilder>b__0(IServiceProvider services)
  at at Discord.Commands.ReflectionUtils.CreateObject[T](TypeInfo typeInfo, CommandService commands, IServiceProvider services)
  at at Discord.Commands.Builders.ModuleBuilder.BuildImpl(CommandService service, IServiceProvider services, ModuleInfo parent)
  at at Discord.Commands.Builders.ModuleBuilder.Build(CommandService service, IServiceProvider services)
  at at Discord.Commands.ModuleClassBuilder.BuildAsync(IEnumerable`1 validTypes, CommandService service, IServiceProvider services)
  at at Discord.Commands.CommandService.AddModulesAsync(Assembly assembly, IServiceProvider services)
  at foo.App.CommandHandler.InstallCommands() in C:\dev\foo\foo.App\CommandHandler.cs:34
```
It would seem that AddModulesAsync also instantiates these modules?

That would actually match what the documentation [here](https://discord.foxbot.me/stable/guides/commands/dependency-injection.html?q=AddModulesAsync) is saying: `Pass the service provider to the second parameter of AddModulesAsync to inject dependencies to all modules that may require them`, but then what is the point of passing the service provider to `ExecuteAsync`?

`Pass the service provider to the ExecuteAsync method for precondition checks` what does "precondition checks" mean?

How do I actually use scoped services inside my modules?

**Comment by Joe4evr** [comment]
> It would seem that AddModulesAsync also instantiates these modules?

We need that so that we can call `OnModuleBuilding`:
https://github.com/discord-net/Discord.Net/blob/a6c1e4c23f71682cba8da2a19038d257b83bd6be/src/Discord.Net.Commands/ModuleBase.cs#L62
To fix this, make sure to also create a scope around your call(s) to `AddModulesAsync`.

**Comment by SubZero0** [comment]
Since Joe already answered, I'll be closing this. Feel free to reopen if you still need help.
