### ISSUE TITLE
Random ObjectDisposedException

### ISSUE THREAD

**Issue by AraHaan** [RogueException/Discord.Net#1575]
I do not use voice channel stuff in my code at all yet now I get this randomly.

```cs
Unhandled exception. System.ObjectDisposedException: The semaphore has been disposed.
   at System.Threading.SemaphoreSlim.CheckDispose()
   at System.Threading.SemaphoreSlim.WaitAsync(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.SemaphoreSlim.WaitAsync()
   at Discord.WebSocket.SocketGuild.DisconnectAudioAsync() in C:\Users\User\Desktop\github\WebApi1\deps\Discord.Net\src\Discord.Net.WebSocket\Entities\Guilds\SocketGuild.cs:line 1016
```

And it seems to happen right after calling ``AddRoles`` with multiple roles.

**Comment by AraHaan** [comment]
Ah it seems related to when one wraps the result from ``client.GetGuild(ulong guildid)`` in an using statement.

**Comment by AraHaan** [comment]
It seems that the IDisposableAnalyzers is wrong to suggest wrapping the result from client.GetGuild in a using statement resulting in this issue.

However if GetGuild returned a clone of the Guild in the internal lists I would be alright to just wrap it in a using statement without Dispose throwing this exception from the DisconnectAudioAsync method.
