### ISSUE TITLE
ISocketAudioChannel.ConnectAsync throws TimeOutException(The operation has timed out.)

### ISSUE THREAD

**Issue by TheBlue-1** [RogueException/Discord.Net#1584]
When I try to connect to an audio channel with
```
ISocketAudioChannel channel = user.AudioChannel();
if (channel == null) {
    throw new ArgumentException("user not in voice channel");
}
IAudioClient client = await channel.ConnectAsync();

//AudioChannel() implemenatation:
public static ISocketAudioChannel AudioChannel(this SocketUser user) {
			IEnumerable<SocketGuildUser> guildUsers = user.MutualGuilds.Select(guild => guild.GetUser(user.Id));
			return guildUsers.FirstOrDefault(guildUser => guildUser.VoiceChannel != null)?.VoiceChannel;
		}
```
i get the Exception:
```
System.AggregateException: One or more errors occurred. (The operation has timed out.)
 ---> System.TimeoutException: The operation has timed out.
   at Discord.WebSocket.SocketGuild.ConnectAudioAsync(UInt64 channelId, Boolean selfDeaf, Boolean selfMute, Boolean external)
   at Discord.WebSocket.SocketGuild.ConnectAudioAsync(UInt64 channelId, Boolean selfDeaf, Boolean selfMute, Boolean external)
   at Discord.WebSocket.SocketVoiceChannel.ConnectAsync(Boolean selfDeaf, Boolean selfMute, Boolean external)
```
I've seen an other issue with the same problem because his command was executed synchron.
I dont use the provided Command Interface, but my method is running async so I think it's another problem.

**Comment by TheBlue-1** [comment]
it happened because i awaited the call in MessageRecieved. The Handler has a timeout.
