### ISSUE TITLE
NullReferenceException in InviteDeleteAuditLogData.Create

### ISSUE THREAD

**Issue by AlexMedia** [RogueException/Discord.Net#1597]
For one of the servers which I help run, I've created a bot which tracks the usage of invites. For the maximum possible accuracy, my bot also traverses the audit log to monitor the creation and deletion of limited use invites.

Due to an unknown reason, yesterday an invite without an owner showed up in the invite list in the Discord client:
![image](https://user-images.githubusercontent.com/948700/89302579-4d015880-d66b-11ea-8cdc-00fcf9ab57ee.png)

When I retrieved this invite programmatically, the `RestInviteMetadata.Inviter` property was null.

After removing this invite, an audit log entry was created for its deletion. My bot can now no longer access the deletion entries as converting the audit log entry fails due to a null reference exception.

My code retrieves the audit log entries as follows:

```c#
var deletedInvites = await guild
                        .GetAuditLogsAsync(limit: int.MaxValue, actionType: ActionType.InviteDeleted)
                        .FlattenAsync();
```

This produces the following error in my logs:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Discord.Rest.InviteDeleteAuditLogData.Create(BaseDiscordClient discord, AuditLog log, AuditLogEntry entry)
   at Discord.Rest.AuditLogHelper.CreateData(BaseDiscordClient discord, AuditLog log, AuditLogEntry entry)
   at Discord.Rest.RestAuditLogEntry..ctor(BaseDiscordClient discord, AuditLog fullLog, AuditLogEntry model, IUser user)
   at Discord.Rest.RestAuditLogEntry.Create(BaseDiscordClient discord, AuditLog fullLog, AuditLogEntry model)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   at Discord.Rest.GuildHelper.<>c__DisplayClass27_0.<<GetAuditLogsAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Discord.PagedAsyncEnumerable`1.Enumerator.MoveNextAsync()
   at System.Linq.AsyncEnumerable.SelectManyAsyncIterator`2.ToListAsync(CancellationToken cancellationToken) in d:\a\1\s\Ix.NET\Source\System.Linq.Async\System\Linq\Operators\SelectMany.cs:line 392
   at System.Linq.AsyncEnumerable.SelectManyAsyncIterator`2.ToListAsync(CancellationToken cancellationToken) in d:\a\1\s\Ix.NET\Source\System.Linq.Async\System\Linq\Operators\SelectMany.cs:line 392
   at System.Linq.AsyncEnumerable.SelectManyAsyncIterator`2.ToArrayAsync(CancellationToken cancellationToken) in d:\a\1\s\Ix.NET\Source\System.Linq.Async\System\Linq\Operators\SelectMany.cs:line 386
   at Discord.AsyncEnumerableExtensions.FlattenAsync[T](IAsyncEnumerable`1 source)
   at REDACTED.GuildInviteService.GetExpectedGuildInvites(SocketGuild guild) in /src/REDACTED/GuildInviteService.cs:line 90
```

This is the JSON data for the delete entry in the audit log:
```json
{
    "id": "REDACTED",
    "user_id": "REDACTED",
    "target_id": null,
    "action_type": 42,
    "changes": [
        {
            "key": "code",
            "old_value": "87xREDACTED"
        },
        {
            "key": "channel_id",
            "old_value": "REDACTED"
        },
        {
            "key": "uses",
            "old_value": 0
        },
        {
            "key": "max_uses",
            "old_value": 0
        },
        {
            "key": "max_age",
            "old_value": 86400
        },
        {
            "key": "temporary",
            "old_value": false
        }
    ]
}
```

**Comment by SubZero0** [comment]
Could you test the PR #1599 ?
