### ISSUE TITLE
Have Context.Guild.GetBanAsync not throw an Discord.Net.HttpException when user is not banned

### ISSUE THREAD

**Issue by OoLunar** [RogueException/Discord.Net#1613]
What I must do right now
```cs
Discord.Rest.RestBan guildUsers = null;
try {
    guildUsers = await Context.Guild.GetBanAsync(banMember);
} catch { }

if(guildUsers != null) // Do some code shenangans
```
What I think should be done
```cs
Discord.Rest.RestBan guildUsers = await Context.Guild.GetBanAsync(banMember);

if(guildUsers != null) // Do some code shenangans
```

Is there a reason why this hasn't been done?

**Comment by jakedacatman** [comment]
Do you have any more information? What is the stack trace? What Discord.Net version?

**Comment by OoLunar** [comment]
Sure! Let me just boot up my bot and get the stack

**Comment by OoLunar** [comment]
Using this piece of code:
```cs
Discord.Rest.RestBan guildUsers = null;
guildUsers = await Context.Guild.GetBanAsync(banMember);
```
I get the error `Exception thrown: 'Discord.Net.HttpException' in System.Private.CoreLib.dll: 'The server responded with error 10026: Unknown Ban'` with stack:
```
   at Discord.Net.Queue.RequestBucket.SendAsync(RestRequest request)
   at Discord.Net.Queue.RequestQueue.SendAsync(RestRequest request)
   at Discord.API.DiscordRestApiClient.SendInternalAsync(String method, String endpoint, RestRequest request)
   at Discord.API.DiscordRestApiClient.SendAsync[TResponse](String method, String endpoint, String bucketId, ClientBucketType clientBucket, RequestOptions options)
   at Discord.API.DiscordRestApiClient.GetGuildBanAsync(UInt64 guildId, UInt64 userId, RequestOptions options)
   at Discord.Rest.GuildHelper.GetBanAsync(IGuild guild, BaseDiscordClient client, UInt64 userId, RequestOptions options)
   at Tomoe.Commands.Moderation.Ban.ByMention(SocketGuildUser banMember, Int32 pruneDays, String reason) in /home/lunar/Code/Dotnet/Tomoe/src/Commands/Moderation/Ban.cs:line 27
```
Discord.NET Version: `<PackageReference Include="Discord.Net" Version="2.2.0" />`

**Comment by jakedacatman** [comment]
Okay, so the PR *fixing* this issue may not be merged for a little while. I recommend something like this for the time being:
```cs
try
{
    Discord.Rest.RestBan guildUsers = null;
    guildUsers = await Context.Guild.GetBanAsync(banMember);
    //do stuff
}
catch (HttpException e) when (e.DiscordCode.HasValue && e.DiscordCode == 10026)
{
    //handle error
}
```

You probably should handle the exception and let the user know the ban was not found, or something.

**Comment by OoLunar** [comment]
I had no idea the `when` keyword was a thing, interesting! I already have a fix made, but I'm glad you offered one to everyone else who might've been having the same issue. Should I keep this issue open to raise awareness, or should I close it?

**Comment by jakedacatman** [comment]
Well the issue hasn't been fixed yet, so I would leave it open for posterity.
