### ISSUE TITLE
Trying to add hash emoji results in 404 from discord server

### ISSUE THREAD

**Issue by DominicEliot** [RogueException/Discord.Net#1653]
The following code will cause a "The server responded with error 404: NotFound" when trying to add the reaction:
```c#
        [Command("MakePostAndReactHash")]
        public async Task MakePostAndReactHash()
        {
            var message = await ReplyAsync("Hello discord.net\nI'm going to try and react with \u0023\u20E3 (:hash:)");
            await message.AddReactionAsync(new Emoji("\u0023\u20E3"));
        }
```
Other similar emojis do work (:one: - \u0031\u20E3)

Stack Trace:
20:50:35 Command     Discord.Commands.CommandException: Error occurred executing "MakePostAndReactHash" for Xeno in Xeno's server/dev-bot.
 ---> Discord.Net.HttpException: The server responded with error 404: NotFound
   at Discord.Net.Queue.RequestBucket.SendAsync(RestRequest request) in .\Discord.Net\src\Discord.Net.Rest\Net\Queue\RequestQueueBucket.cs:line 114
   at Discord.Net.Queue.RequestQueue.SendAsync(RestRequest request) in .\Discord.Net\src\Discord.Net.Rest\Net\Queue\RequestQueue.cs:line 86
   at Discord.API.DiscordRestApiClient.SendInternalAsync(String method, String endpoint, RestRequest request) in .\Discord.Net\src\Discord.Net.Rest\DiscordRestApiClient.cs:line 270
   at Discord.API.DiscordRestApiClient.SendAsync(String method, String endpoint, BucketId bucketId, ClientBucketType clientBucket, RequestOptions options) in .\Discord.Net\src\Discord.Net.Rest\DiscordRestApiClient.cs:line 188
   at Discord.API.DiscordRestApiClient.AddReactionAsync(UInt64 channelId, UInt64 messageId, String emoji, RequestOptions options) in .\Discord.Net\src\Discord.Net.Rest\DiscordRestApiClient.cs:line 634
   at Discord.Rest.MessageHelper.AddReactionAsync(IMessage msg, IEmote emote, BaseDiscordClient client, RequestOptions options) in .\Discord.Net\src\Discord.Net.Rest\Entities\Messages\MessageHelper.cs:line 68
   at TestBot.Core.TestCommands.MakePostAndReactHash() in .\TestBot\Core\TestCommands.cs:line 5
   at Discord.Commands.ModuleClassBuilder.<>c__DisplayClass6_0.<<BuildCommand>g__ExecuteCallback|0>d.MoveNext() in .\Discord.Net\src\Discord.Net.Commands\Builders\ModuleClassBuilder.cs:line 220
--- End of stack trace from previous location where exception was thrown ---
   at Discord.Commands.CommandInfo.ExecuteInternalAsync(ICommandContext context, Object[] args, IServiceProvider services) in .\Discord.Net\src\Discord.Net.Commands\Info\CommandInfo.cs:line 249
   --- End of inner exception stack trace ---

**Comment by xXBuilderBXx** [comment]
I noticed on the repo there is a branch that is supposed to validate emotes https://github.com/discord-net/Discord.Net/tree/experiment/emoji-validation

**Comment by TH3AL3X** [comment]
Check this: https://stackoverflow.com/questions/46740554/discord-net-adding-reactions-to-a-socketmessage

**Comment by DominicEliot** [comment]
> 
> 
> Check this: https://stackoverflow.com/questions/46740554/discord-net-adding-reactions-to-a-socketmessage

I'm not sure how that helps. Using the emoji has the is same result as the unicode.
