### ISSUE TITLE
SendMessageAsync throws System.TimeoutException

### ISSUE THREAD

**Issue by RheaAyase** [RogueException/Discord.Net#1680]
Been seeing these sometimes more often, sometimes less, but they happen quite often. Relatively speaking ;)

Not sure what the cause could be, I doubt that it's a network issue, monitoring would catch that. They do seem to come in sort of clusters of a few in a minute or two...

Stack: 
```
   at Discord.Net.Queue.RequestBucket.EnterAsync(Int32 id, RestRequest request)
   at Discord.Net.Queue.RequestBucket.SendAsync(RestRequest request)
   at Discord.Net.Queue.RequestQueue.SendAsync(RestRequest request)
   at Discord.API.DiscordRestApiClient.SendInternalAsync(String method, String endpoint, RestRequest request)
   at Discord.API.DiscordRestApiClient.SendJsonAsync[TResponse](String method, String endpoint, Object payload, BucketId bucketId, ClientBucketType clientBucket, RequestOptions options)
   at Discord.API.DiscordRestApiClient.CreateMessageAsync(UInt64 channelId, CreateMessageParams args, RequestOptions options)
   at Discord.Rest.ChannelHelper.SendMessageAsync(IMessageChannel channel, BaseDiscordClient client, String text, Boolean isTTS, Embed embed, AllowedMentions allowedMentions, RequestOptions options)
```

**Comment by RheaAyase** [comment]
I'm also observing that these always repeat on the same guild ID's - I wonder if it's some silent failure on permissions or something along those lines.

**Comment by SubZero0** [comment]
Did you change your Timeout in the RequestOptions?

I was wondering if this is related to bucket redirection, but there's only one call to both `RequestBucket.SendAsync` and `RequestBucket.EnterAsync`.

I did notice the RetryTimeouts might not be working as expected considering this context:
Request is done -> Http client timeouts the request after the timeout limit (15s by default) -> Falls on `catch (TimeoutException)` that will retry it -> `EnterAsync` will throw `new TimeoutException();` since it's already past it.
But this would also include another call to `RequestBucket.EnterAsync`.

It seems to be a "natural" http client timeout for me atm.

**Comment by RheaAyase** [comment]
No the timeout is default.

**Comment by quinchs** [comment]
Did you resolve this or did v2.4.0 fix this?
