### ISSUE TITLE
NullReferenceException when mentioning an user in direct message

### ISSUE THREAD

**Issue by ObiOneStenobi** [RogueException/Discord.Net#1696]
Whenever an user, self or the bot (used for mention prefix), is mentioned in the DM channel , it throws this error:
```
[Error] Gateway: Error handling Dispatch (MESSAGE_CREATE) System.NullReferenceException: Object reference not set to an instance of an object.
   at Discord.WebSocket.SocketUserMessage.Update(ClientState state, Message model)
   at Discord.WebSocket.SocketUserMessage.Create(DiscordSocketClient discord, ClientState state, SocketUser author, ISocketMessageChannel channel, Message model)
   at Discord.WebSocket.SocketMessage.Create(DiscordSocketClient discord, ClientState state, SocketUser author, ISocketMessageChannel channel, Message model)
   at Discord.WebSocket.DiscordSocketClient.ProcessMessageAsync(GatewayOpCode opCode, Nullable`1 seq, String type, Object payload)
```

This will abort the operation and obviously will not fire the **Message Received** event, making the mention prefix useless in DM channels.

**Comment by SubZero0** [comment]
Thanks for reporting, should be fixed by 5ed01a30b6c25da65e5c401bf6b7ed8fbb939926.
