### ISSUE TITLE
LoginAsync throws System.TimeoutException

### ISSUE THREAD

**Issue by atmuccio** [RogueException/Discord.Net#1710]
Attempting to login from Azure WebJob results in a System.TimeoutException. This particular run was using v2.1.1 for Discord.Net however I have tried with the latest version and have received the same outcome. I have used both of these versions for several weeks without issue, but now this is consistently happening.

The app is currently using default settings for rates.
The app has been working for roughly a year with no issues with this login, but in the past week or two this has been consistently failing.

I'm not willing to say with 100% certainty that this is a Discord.Net issue due to the fact I can run the bot from my house with no issues while it fails in the cloud, but I have seen a similar issue related to the RequestBucket call.

https://github.com/discord-net/Discord.Net/issues/1680

```
[12/12/2020 20:00:00] Status changed to Initializing
[12/12/2020 20:00:00] Status changed to Running
[12/12/2020 20:00:02] 08:00:02 [Info] Discord: Discord.Net v2.1.1 (API v6)
[12/12/2020 20:00:02] 08:00:02 [Warning] Rest: Rate limit triggered: voice/regions
[12/12/2020 20:00:07] 08:00:07 [Warning] Rest: Rate limit triggered: voice/regions
[12/12/2020 20:00:12] 08:00:12 [Warning] Rest: Rate limit triggered: voice/regions
[12/12/2020 20:00:17] 08:00:17 [Warning] Rest: Rate limit triggered: voice/regions
[12/12/2020 20:00:18] Unhandled exception. System.TimeoutException: The operation has timed out.
[12/12/2020 20:00:18]    at Discord.Net.Queue.RequestBucket.EnterAsync(Int32 id, RestRequest request)
[12/12/2020 20:00:18]    at Discord.Net.Queue.RequestBucket.SendAsync(RestRequest request)
[12/12/2020 20:00:18]    at Discord.Net.Queue.RequestQueue.SendAsync(RestRequest request)
[12/12/2020 20:00:18]    at Discord.API.DiscordRestApiClient.SendInternalAsync(String method, String endpoint, RestRequest request)
[12/12/2020 20:00:18]    at Discord.API.DiscordRestApiClient.SendAsync[TResponse](String method, String endpoint, String bucketId, ClientBucketType clientBucket, RequestOptions options)
[12/12/2020 20:00:18]    at Discord.API.DiscordRestApiClient.GetVoiceRegionsAsync(RequestOptions options)
[12/12/2020 20:00:18]    at Discord.WebSocket.DiscordSocketClient.OnLoginAsync(TokenType tokenType, String token)
[12/12/2020 20:00:18]    at Discord.Rest.BaseDiscordClient.LoginInternalAsync(TokenType tokenType, String token, Boolean validateToken)
[12/12/2020 20:00:18]    at Discord.Rest.BaseDiscordClient.LoginInternalAsync(TokenType tokenType, String token, Boolean validateToken)
[12/12/2020 20:00:18]    at Discord.Rest.BaseDiscordClient.LoginAsync(TokenType tokenType, String token, Boolean validateToken)
```

**Comment by SubZero0** [comment]
You reached a ratelimit, its not a bug. But that rest request was removed when starting the client in 5934c7949a03d492dfc85c94c2c4fc920aaba670, so I would recommend using the latest nightly. If it happens again, just ask us to reopen this issue.

**Comment by atmuccio** [comment]
Sounds great! I saw I was hitting a limit but was unsure if it was related to the retry timeouts. It would appear this issue was being caused by the environment my host was using. This request was only failing in their vms. I'll for sure give this a try, but moving to a host I had more control over seems to also be working.

Thank you!
