### ISSUE TITLE
Trying to set bot's username/avatar results in HttpException: 400 BadRequest

### ISSUE THREAD

**Issue by JOBBIN9422** [RogueException/Discord.Net#1808]
# Summary
Trying to set the bot's username and/or avatar via `ModifyAsync` on its current user object throws an HttpException: `400 BadRequest`.
```csharp
[Command("reset", RunMode = RunMode.Async)]
[Summary("Reset the bot's avatar and nickname.")]
public async Task ResetBotAvatarAndUsername()
{
    await _bot.Client.CurrentUser.ModifyAsync(x =>
    {
        x.Username = "Terminus.NET";
        x.Avatar = new Image(Path.Combine("assets", "images", "terminus.jpg"));
    });
}
```
# Details
- .NET version: `5.0`
- Discord.NET version: `2.3.1`

Stack trace:
```
Discord.Net.HttpException: The server responded with error 400: BadRequest
   at Discord.Net.Queue.RequestBucket.SendAsync(RestRequest request)
   at Discord.Net.Queue.RequestQueue.SendAsync(RestRequest request)
   at Discord.API.DiscordRestApiClient.SendInternalAsync(String method, String endpoint, RestRequest request)
   at Discord.API.DiscordRestApiClient.SendJsonAsync[TResponse](String method, String endpoint, Object payload, BucketId bucketId, ClientBucketType clientBucket, RequestOptions options)
   at Discord.API.DiscordRestApiClient.ModifySelfAsync(ModifyCurrentUserParams args, RequestOptions options)
   at Discord.Rest.UserHelper.ModifyAsync(ISelfUser user, BaseDiscordClient client, Action`1 func, RequestOptions options)
```

# Notes
- Sometimes, the request does not get a response for several minutes. 
- Sometimes, the nickname is set but the avatar is never updated.
- The image I'm attempting to use is 8.9KB (300 x 204).

**Comment by quinchs** [comment]
I'm unable to repo this issue. Can you verify these things:
* Are you positive that `Path.Combine("assets", "images", "terminus.jpg")` is a valid path and the bot can read the file?
* What log level are you using? If you set it to `LogLevel.Debug` does anything else print in the console when trying the request.
