### ISSUE TITLE
HttpException 500 in UserVoiceStateUpdated Event

### ISSUE THREAD

**Issue by Sh00ter0** [RogueException/Discord.Net#1817]
Hello. I have a problem in the UserVoiceStateUpdated event. For reasons unknown to me, this is the only place where I appear. Does anyone know the answer what can cause such an error? 

```
Discord.Net.HttpException: The server responded with error 500: 500: Internal Server Error
   at Discord.Net.Queue.RequestBucket.SendAsync(RestRequest request)
   at Discord.Net.Queue.RequestQueue.SendAsync(RestRequest request)
   at Discord.API.DiscordRestApiClient.SendInternalAsync(String method, String endpoint, RestRequest request)
   at Discord.API.DiscordRestApiClient.SendJsonAsync[TResponse](String method, String endpoint, Object payload, BucketId bucketId, ClientBucketType clientBucket, RequestOptions options)
   at Discord.API.DiscordRestApiClient.CreateMessageAsync(UInt64 channelId, CreateMessageParams args, RequestOptions options)
   at Discord.Rest.ChannelHelper.SendMessageAsync(IMessageChannel channel, BaseDiscordClient client, String text, Boolean isTTS, Embed embed, AllowedMentions allowedMentions, MessageReference messageReference, RequestOptions options)
   at Discord.WebSocket.SocketTextChannel.Discord.IMessageChannel.SendMessageAsync(String text, Boolean isTTS, Embed embed, RequestOptions options, AllowedMentions allowedMentions, MessageReference messageReference)
```

**Comment by zbroderson** [comment]
5XX errors indicate an error on discord's servers.  Likely nothing to do with you, but in any case its their issue.

Could also be an outage

**Comment by Sh00ter0** [comment]
Thank you for your help.
