### ISSUE TITLE
Modifing SocketTextChannel.SlowModeInterval works only if bot has GuildPermission.Administrator

### ISSUE THREAD

**Issue by JerzyKruszewski** [RogueException/Discord.Net#1824]
Hi I wrote this piece of code
```
        [Command("Slowmode", RunMode = RunMode.Async)]
        [RequireStaff]
        [RequireBotPermission(GuildPermission.ManageChannels)]
        public async Task Slowmode(int interval, params SocketTextChannel[] channels)
        {
            SocketGuild guild = Context.Guild;
            GuildConfig config = new GuildConfigs(guild.Id, _storage).GetGuildConfig();
            AlertsHandler alerts = new AlertsHandler(config);
            
            foreach (SocketTextChannel channel in channels)
            {
                //code will stop executing on ModifyAsync
                await channel.ModifyAsync(c => 
                {
                    c.SlowModeInterval = interval; 
                });
                await Task.Delay(250);
            }

            await Context.Channel.SendMessageAsync(alerts.GetAlert("SUCCESS"));
        }
```
But it doesn't work until bot will have actual administrator privileges.
Am I doing something wrong? Or it really require admin privileges?

Discord.Net version: 2.3.0 and 2.3.1

I tried to enable every other guild permission on bot role other than Administrator with no result.

I added try...catch on ModifyAsync and got this Exception (all guild permission except Administrator):
```
Discord.Net.HttpException: The server responded with error 50013: Missing Permissions
   at Discord.Net.Queue.RequestBucket.SendAsync(RestRequest request)
   at Discord.Net.Queue.RequestQueue.SendAsync(RestRequest request)
   at Discord.API.DiscordRestApiClient.SendInternalAsync(String method, String endpoint, RestRequest request)
   at Discord.API.DiscordRestApiClient.SendJsonAsync[TResponse](String method, String endpoint, Object payload, BucketId bucketId, ClientBucketType clientBucket, RequestOptions options)
   at Discord.API.DiscordRestApiClient.ModifyGuildChannelAsync(UInt64 channelId, ModifyTextChannelParams args, RequestOptions options)
   at Discord.Rest.ChannelHelper.ModifyAsync(ITextChannel channel, BaseDiscordClient client, Action`1 func, RequestOptions options)
   at RachelBot.Commands.ModerationCommands.Slowmode(Int32 interval, SocketTextChannel[] channels) in F:\Discord Bots\RachelDiscordBot\RachelBot\Commands\ModerationCommands.cs:line 457```

**Comment by zbroderson** [comment]
Theoretically, you should be able to modify the channel with ManageChannels (from what I know), but in any case this isn't a dnet issue as discord's servers are kicking that error back to you.

**Comment by JerzyKruszewski** [comment]
```
                    if (channel.GetPermissionOverwrite(Context.Client.CurrentUser).Value.ManageChannel == PermValue.Allow)
                    {
                        await channel.ModifyAsync(c =>
                        {
                            c.SlowModeInterval = interval;
                        });
                    }
```
Adding this piece of code and added my bot (not role) to ménage channel, and it worked.
Any idea where I could report API issue?

**Comment by JerzyKruszewski** [comment]
Issue identified: It was my mistake.
In channel permissions everyone (with my bot) had denied permissions to manage channel.
