### ISSUE TITLE
Some gateway dispatches cause InvalidOperationException

### ISSUE THREAD

**Issue by ABCRic** [RogueException/Discord.Net#1870]
My bot has been randomly emiting the following error traces every so often since a recent update (currently running version 3.0.0-dev-20210601.2):

```
23:10:49 Shard #1    Error handling Dispatch (TYPING_START):
System.InvalidOperationException: This operation cannot be performed on a default instance of ImmutableArray<T>.  Consider initializing the array, or checking the ImmutableArray<T>.IsDefault property.
   at System.Collections.Immutable.ImmutableArray`1.ThrowInvalidOperationIfNotInitialized()
   at System.Collections.Immutable.ImmutableArray`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at Discord.Permissions.ResolveGuild(IGuild guild, IGuildUser user)
   at Discord.WebSocket.SocketTextChannel.GetUser(UInt64 id)
   at Discord.WebSocket.DiscordSocketClient.ProcessMessageAsync(GatewayOpCode opCode, Nullable`1 seq, String type, Object payload)
```

This most often happens with TYPING_START but it can also happen with others, e.g.
```
23:14:55 Shard #0    Error handling Dispatch (MESSAGE_CREATE):
System.InvalidOperationException: This operation cannot be performed on a default instance of ImmutableArray<T>.  Consider initializing the array, or checking the ImmutableArray<T>.IsDefault property.
   at System.Collections.Immutable.ImmutableArray`1.ThrowInvalidOperationIfNotInitialized()
   at System.Collections.Immutable.ImmutableArray`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at Discord.Permissions.ResolveGuild(IGuild guild, IGuildUser user)
   at Discord.WebSocket.SocketTextChannel.GetUser(UInt64 id)
   at Discord.WebSocket.SocketGuildChannel.Discord.IChannel.GetUserAsync(UInt64 id, CacheMode mode, RequestOptions options)
   at Discord.WebSocket.SocketUserMessage.Update(ClientState state, Message model)
   at Discord.WebSocket.SocketUserMessage.Create(DiscordSocketClient discord, ClientState state, SocketUser author, ISocketMessageChannel channel, Message model)
   at Discord.WebSocket.DiscordSocketClient.ProcessMessageAsync(GatewayOpCode opCode, Nullable`1 seq, String type, Object payload)
```

```
23:15:20 Shard #0    Error handling Dispatch (MESSAGE_REACTION_ADD):
System.InvalidOperationException: This operation cannot be performed on a default instance of ImmutableArray<T>.  Consider initializing the array, or checking the ImmutableArray<T>.IsDefault property.
   at System.Collections.Immutable.ImmutableArray`1.ThrowInvalidOperationIfNotInitialized()
   at System.Collections.Immutable.ImmutableArray`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at Discord.Permissions.ResolveGuild(IGuild guild, IGuildUser user)
   at Discord.WebSocket.SocketTextChannel.GetUser(UInt64 id)
   at Discord.WebSocket.SocketGuildChannel.Discord.IChannel.GetUserAsync(UInt64 id, CacheMode mode, RequestOptions options)
   at Discord.WebSocket.DiscordSocketClient.ProcessMessageAsync(GatewayOpCode opCode, Nullable`1 seq, String type, Object payload)
```

I have all gateway intents enabled, if it makes a difference (bot is verified and has both privileged intents).

**Comment by zbroderson** [comment]
Afaik 3.0 is very experimental at the moment and has no official release.  Your probably best off with sticking to the latest stable release.

**Comment by SubZero0** [comment]
I believe the roles are missing so they are never initialized and might be throwing, from something like this:

1. Some event adds the new guild user without initializing the roles
2. Other event is received and calls `channel.GetUser`, the channel in the case would be a `SocketTextChannel`.
3. `SocketTextChannel.GetUser` will resolve the permissions, since the roles aren't initialized for that user, it throws that exception.

So the issue would be finding the event adding an invalid user.
From looking the events and since I didn't have the presence intents enabled, my guess atm is `PRESENCE_UPDATE` missing the roles, since everything is optional.

I will still need to try to repro, but I can see two fixes if it's really that:
1. Add an empty role list (might be bad because people could try to use this cached user somewhere else and it would be wrong)
2. Not cache the user, just create it for this event.

**Comment by SubZero0** [comment]
I wasn't able to repro this issue, would you be able to locally test #1871 and see if it fixes your issues?

**Comment by expeehaa** [comment]
I have the same issue and #1871 seems to have solved it. I will keep observing it though in case it happens again.

**Comment by SubZero0** [comment]
I might need to find what event (or specific case for an event) is causing this issue since that PR is more of a workaround.
