### ISSUE TITLE
Can't login Succesful as of now

### ISSUE THREAD

**Issue by DefaultO** [RogueException/Discord.Net#1900]
Kinda wanted to code an *Anti Steam Quit Scam Bot* today but happened to get the same Error Message in every Wrapper I tried today. The Token is not wrong. I used the Copy Button from the Developer Portals Page. What my other guess was is that Discord didn't accept the Request due to low-security something. This could have been fixed by putting this
```csharp
ServicePointManager.SecurityProtocol = SecurityProtocolType.Ssl3 | SecurityProtocolType.Tls | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;
```
above the creation of the HttpClient. But then I realized, there is no HttpClient in the whole project that could have been found using the Visual Studio Search feature. So now I am stuck with an error, that I am the only one to get seemingly, as it can't be found on Google anywhere.

I've tried to run the "ping" Example Project, code of it can be found [**HERE**](https://github.com/discord-net/Discord.Net/blob/dev/samples/01_basic_ping_bot/Program.cs). It shouldn't be such a bad code that it spawns that exception, since I've seen a repository containing the basic structure of it too, which has been updated 5 hours ago.

Message inside the InnerExceptions: **``The Format of the received Message was unexpected or false``** (translated from German)

![image](https://user-images.githubusercontent.com/42414542/127545813-28683a71-2a30-4a92-96bc-973229e1ac24.png)

Console Output:
```js
20:05:17 Discord     Discord.Net v3.0.0-dev-dev (API v9)
20:05:17 Gateway     Connecting
20:05:18 Gateway     System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The read operation failed, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> System.ComponentModel.Win32Exception (0x80090326): Das Format der empfangenen Nachricht war unerwartet oder fehlerhaft.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ReplyOnReAuthentication(Byte[] buffer, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Discord.Net.Rest.DefaultRestClient.SendInternalAsync(HttpRequestMessage request, CancellationToken cancelToken, Boolean headerOnly) in C:\Users\breit\Downloads\Discord.Net-dev\Discord.Net-dev\src\Discord.Net.Rest\Net\DefaultRestClient.cs:line 139
   at Discord.Net.Rest.DefaultRestClient.SendAsync(String method, String endpoint, CancellationToken cancelToken, Boolean headerOnly, String reason) in C:\Users\breit\Downloads\Discord.Net-dev\Discord.Net-dev\src\Discord.Net.Rest\Net\DefaultRestClient.cs:line 74
   at Discord.Net.Queue.RestRequest.SendAsync() in C:\Users\breit\Downloads\Discord.Net-dev\Discord.Net-dev\src\Discord.Net.Rest\Net\Queue\Requests\RestRequest.cs:line 31
   at Discord.Net.Queue.RequestBucket.SendAsync(RestRequest request) in C:\Users\breit\Downloads\Discord.Net-dev\Discord.Net-dev\src\Discord.Net.Rest\Net\Queue\RequestQueueBucket.cs:line 67
   at Discord.Net.Queue.RequestQueue.SendAsync(RestRequest request) in C:\Users\breit\Downloads\Discord.Net-dev\Discord.Net-dev\src\Discord.Net.Rest\Net\Queue\RequestQueue.cs:line 86
   at Discord.API.DiscordRestApiClient.SendInternalAsync(String method, String endpoint, RestRequest request) in C:\Users\breit\Downloads\Discord.Net-dev\Discord.Net-dev\src\Discord.Net.Rest\DiscordRestApiClient.cs:line 266
   at Discord.API.DiscordRestApiClient.SendAsync[TResponse](String method, String endpoint, BucketId bucketId, ClientBucketType clientBucket, RequestOptions options) in C:\Users\breit\Downloads\Discord.Net-dev\Discord.Net-dev\src\Discord.Net.Rest\DiscordRestApiClient.cs:line 226
   at Discord.API.DiscordRestApiClient.GetGatewayAsync(RequestOptions options) in C:\Users\breit\Downloads\Discord.Net-dev\Discord.Net-dev\src\Discord.Net.Rest\DiscordRestApiClient.cs:line 286
   at Discord.API.DiscordSocketApiClient.ConnectInternalAsync() in C:\Users\breit\Downloads\Discord.Net-dev\Discord.Net-dev\src\Discord.Net.WebSocket\DiscordSocketApiClient.cs:line 153
   at Discord.API.DiscordSocketApiClient.ConnectInternalAsync() in C:\Users\breit\Downloads\Discord.Net-dev\Discord.Net-dev\src\Discord.Net.WebSocket\DiscordSocketApiClient.cs:line 165
   at Discord.API.DiscordSocketApiClient.ConnectAsync() in C:\Users\breit\Downloads\Discord.Net-dev\Discord.Net-dev\src\Discord.Net.WebSocket\DiscordSocketApiClient.cs:line 122
   at Discord.WebSocket.DiscordSocketClient.OnConnectingAsync() in C:\Users\breit\Downloads\Discord.Net-dev\Discord.Net-dev\src\Discord.Net.WebSocket\DiscordSocketClient.cs:line 223
   at Discord.ConnectionManager.ConnectAsync(CancellationTokenSource reconnectCancelToken) in C:\Users\breit\Downloads\Discord.Net-dev\Discord.Net-dev\src\Discord.Net.WebSocket\ConnectionManager.cs:line 141
   at Discord.ConnectionManager.<>c__DisplayClass29_0.<<StartAsync>b__0>d.MoveNext() in C:\Users\breit\Downloads\Discord.Net-dev\Discord.Net-dev\src\Discord.Net.WebSocket\ConnectionManager.cs:line 74
20:05:18 Gateway     Disconnecting
20:05:18 Gateway     Disconnected
```

**Comment by quinchs** [comment]
We're also experiencing the same issues, although no stack trace. it just hangs at `StartAsync`

**Comment by DefaultO** [comment]
Forgot to reply. The issue is resolved. My problem was issued because I used the wrong Project Type. Console Application is not equal to Console Application, even if both are templates for a C# application. Make sure to pick the .NET Framework one instead of the other one if you encounter the same issue.

![image](https://user-images.githubusercontent.com/42414542/132103295-195e5f2f-b791-4b69-b869-7227fbd92df4.png)

Your issue must be something else @quinchs. I am sorry to hear that. Hope it resolved itself as well. Closing this now.

**Comment by zbroderson** [comment]
Despite this solving your issue using .NET Framework is not advised.  .NET Core (now just .NET) is new, shinier and is the future and focus of the .NET team moving forward.  .NET Framework is essentially discontinued and deprecated now.

**Comment by DefaultO** [comment]
> Despite this solving your issue using .NET Framework is not advised. .NET Core (now just .NET) is new, shinier and is the future and focus of the .NET team moving forward. .NET Framework is essentially discontinued and deprecated now.

Yea. I use ``.NET 5`` myself usually. But if I know that only I will run the application, and I don't care about cross-platform support, I don't mind choosing ``.NET Framework 4.8`` over ``.NET``. For API Client's I prefer .NET (Core) though, even if all above applies.

I got this old idea of .NET Core in my head for just being the Core Components of the .NET Framework. Even if this doesn't apply any more (or still does?).

Overall that's like telling me WinForms is deprecated, and it definitely is, and it is way more limited than WPF, I know all of that, but I still use WinForms for whatever reason.
