### ISSUE TITLE
TimeoutException with RetryMode.RetryTimeouts

### ISSUE THREAD

**Issue by Lukazoid** [RogueException/Discord.Net#1952]
With the following:

```
var requestOptions = new RequestOptions
{
    CancelToken = cancellationToken,
    RetryMode = RetryMode.AlwaysRetry,
    AuditLogReason = "retrieving participant guilds"
};

var guilds = await discordClient.GetGuildsAsync(requestOptions).ConfigureAwait(false);
```

I am on occasion receiving the following exception:

> System.TimeoutException: The operation has timed out.
>    at Discord.Net.Queue.RequestBucket.EnterAsync(Int32 id, IRequest request)
>    at Discord.Net.Queue.RequestBucket.SendAsync(RestRequest request)
>    at Discord.Net.Queue.RequestQueue.SendAsync(RestRequest request)
>    at Discord.API.DiscordRestApiClient.SendInternalAsync(String method, String endpoint, RestRequest request)
>    at Discord.API.DiscordRestApiClient.SendAsync[TResponse](String method, String endpoint, BucketId bucketId, ClientBucketType clientBucket, RequestOptions options)
>    at Discord.API.DiscordRestApiClient.GetGuildChannelsAsync(UInt64 guildId, RequestOptions options)
>    at Discord.Rest.GuildHelper.GetChannelsAsync(IGuild guild, BaseDiscordClient client, RequestOptions options)
>    at Discord.Rest.RestGuild.GetCategoryChannelsAsync(RequestOptions options)

However I can see `RetryMode.AlwaysRetry` includes `RetryMode.RetryTimeouts` so I would have thought the timeout should have been retried?

**Comment by Lukazoid** [comment]
Ah, was my misunderstanding, the timeout referred to by `RetryMode` is for API timeouts, while this timeout is being caused by the default 15 second setting of `RequestOptions.Timeout`, setting  `requestOptions.Timeout = null` appears to solve it.
