### ISSUE TITLE
SocketException and 100 % CPU usage

### ISSUE THREAD

**Issue by Mailaender** [RogueException/Discord.Net#1956]
My https://github.com/OpenHV/HardVacuumRobot runs on a https://cloud.google.com `e2-micro` instance, which is more than enough when it runs like it should. However, after some runtime it clogs up 100% CPU usage, the bot is disconnected and the instance becomes unresponsive.

It spams this failed attempt every minute

```
---> System.Net.Sockets.SocketException (11): Resource temporarily unavailable
  at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
  --- End of inner exception stack trace ---
  at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
  at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
  at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
  at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
  at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationT>
  at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
  at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
  at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean dis>
  at Discord.Net.Rest.DefaultRestClient.SendInternalAsync(HttpRequestMessage request, CancellationToken cancelToken, Boolean headerOnly)
  at Discord.Net.Rest.DefaultRestClient.SendAsync(String method, String endpoint, CancellationToken cancelToken, Boolean headerOnly, String r>
  at Discord.Net.Queue.RestRequest.SendAsync()
  at Discord.Net.Queue.RequestBucket.SendAsync(RestRequest request)
  at Discord.Net.Queue.RequestQueue.SendAsync(RestRequest request)
  at Discord.API.DiscordRestApiClient.SendInternalAsync(String method, String endpoint, RestRequest request)
  at Discord.API.DiscordRestApiClient.SendAsync[TResponse](String method, String endpoint, BucketId bucketId, ClientBucketType clientBucket, >
  at Discord.API.DiscordRestApiClient.GetGatewayAsync(RequestOptions options)
  at Discord.API.DiscordSocketApiClient.ConnectInternalAsync()
  at Discord.API.DiscordSocketApiClient.ConnectInternalAsync()
  at Discord.API.DiscordSocketApiClient.ConnectAsync()
  at Discord.WebSocket.DiscordSocketClient.OnConnectingAsync()
  at Discord.ConnectionManager.ConnectAsync(CancellationTokenSource reconnectCancelToken)
  at Discord.ConnectionManager.<>c__DisplayClass29_0.<<StartAsync>b__0>d.MoveNext()
```

Is there a way to make it reconnect maybe in > 60 seconds intervals?

**Comment by Mailaender** [comment]
I got the feeling this is actually a memory leak on my side. This stack trace is not the source of the problem.
