### ISSUE TITLE
IMessage.Resolve does not work in DMs

### ISSUE THREAD

**Issue by jyrka98** [RogueException/Discord.Net#198]
Throws exception:
```
System.NullReferenceException: Object reference not set to an instance of an object.
at Discord.MentionUtils.ResolveChannelMentions(String text, IGuild guild, ChannelMentionHandling mode)
at Discord.Rest.Message.Resolve(String text, UserMentionHandling userHandling, ChannelMentionHandling channelHandling, RoleMentionHandling roleHandling, EveryoneMentionHandling everyoneHandling)
at Discord.Rest.Message.Resolve(UserMentionHandling userHandling, ChannelMentionHandling channelHandling, RoleMentionHandling roleHandling, EveryoneMentionHandling everyoneHandling)
```

**Comment by khionu** [comment]
I've reproduced, we'll fix it as soon as we can

**Comment by RogueException** [comment]
Please let me know if https://github.com/RogueException/Discord.Net/commit/7b130f65281ac3edff56124719af47e7ac9963dc fixes the problem for you

**Comment by jyrka98** [comment]
It works now, thanks. :smile:
