### ISSUE TITLE
System.TimeoutException: Cannot respond to an interaction after 3 seconds!

### ISSUE THREAD

**Issue by MaxEtMoritz** [RogueException/Discord.Net#2010]
Today i tried to make first steps with Interaction commands by creating a slash command that responds with predefined text, similar to the ping slash command in the examples.
But when i try to `RespondAsync(...)`, i get a `System.TimeoutException` with the text `Cannot respond to an interaction after 3 seconds!`
The strange thing is: This Exception occurs right after the slash command was sent in the Discord client, not just after 3 or more seconds of waiting.
Thinking i've done something wrong, i cloned the examples from this Repo and run example `04_interactions_framework`.
But the same thing happens there (if i supply the same bot token and testGuild ID, did not try to create different Bot account or test guild yet).
Does anyone have an idea what could be wrong?

If it helps: This is the Stack trace when executing `/echo echo!` in the example 04_interactions_framework:
```
System.TimeoutException: Cannot respond to an interaction after 3 seconds!
   at Discord.WebSocket.SocketCommandBase.RespondAsync(String text, Embed[] embeds, Boolean isTTS, Boolean ephemeral, AllowedMentions allowedMentions, MessageComponent components, Embed embed, RequestOptions options)
   at Discord.WebSocket.SocketInteraction.Discord.IDiscordInteraction.RespondAsync(String text, Embed[] embeds, Boolean isTTS, Boolean ephemeral, AllowedMentions allowedMentions, MessageComponent components, Embed embed, RequestOptions options)
   at Discord.Interactions.InteractionModuleBase`1.RespondAsync(String text, Embed[] embeds, Boolean isTTS, Boolean ephemeral, AllowedMentions allowedMentions, RequestOptions options, MessageComponent components, Embed embed)
   at _04_interactions_framework.Modules.UtilityModule.Echo(String echo, Boolean mention) in C:\Users\[...]\04_interactions_framework\Modules\UtilityModule.cs:line 43
   at Discord.Interactions.Builders.ModuleClassBuilder.<>c__DisplayClass10_0.<<CreateCallback>g__ExecuteCallback|1>d.MoveNext()
```
This is a part of the log from my own Bot, with more accurate timestamp display and LogLevel set to Verbose.
The second Error: Unknown Webhook happens in my post-execution logic (that i just copied from the text-based commands), so you can safely ignore it for now as it is probably not directly related to the problem.
```
2021-12-29 19:53:19 Gateway     Debug    Received Dispatch (INTERACTION_CREATE)
2021-12-29 19:53:19 HandleInter Debug    HandleInteraction Called.
2021-12-29 19:53:19 ShowHelpAsy Debug    Command Module called.
2021-12-29 19:53:19 App Command Error     System.TimeoutException: Cannot respond to an interaction after 3 seconds!
   at Discord.WebSocket.SocketCommandBase.RespondAsync(String text, Embed[] embeds, Boolean isTTS, Boolean ephemeral, AllowedMentions allowedMentions, MessageComponent components, Embed embed, RequestOptions options)
   at CompanionBot.TestModules.ShowHelpAsync(String WhatYouWannaKnow) in C:\Users\[...]\SlashCommandModules.cs:line 21
   at Discord.Interactions.Builders.ModuleClassBuilder.<>c__DisplayClass10_0.<<CreateCallback>g__ExecuteCallback|1>d.MoveNext()
2021-12-29 19:53:19 CommandExec Debug    CommandExecuted Handler called.
2021-12-29 19:53:19 help        Warning  Interaction error in guild Testserver Webhook (781826303128371241): Cannot respond to an interaction after 3 seconds!
2021-12-29 19:53:20 App Command Error     Discord.Net.HttpException: The server responded with error 10015: Unknown Webhook
   at Discord.Net.Queue.RequestBucket.SendAsync(RestRequest request)
   at Discord.Net.Queue.RequestQueue.SendAsync(RestRequest request)
   at Discord.API.DiscordRestApiClient.SendInternalAsync(String method, String endpoint, RestRequest request)
   at Discord.API.DiscordRestApiClient.SendJsonAsync[TResponse](String method, String endpoint, Object payload, BucketId bucketId, ClientBucketType clientBucket, RequestOptions options)
   at Discord.API.DiscordRestApiClient.CreateInteractionFollowupMessageAsync(CreateWebhookMessageParams args, String token, RequestOptions options)
   at Discord.Rest.InteractionHelper.SendFollowupAsync(BaseDiscordClient client, CreateWebhookMessageParams args, String token, IMessageChannel channel, RequestOptions options)
   at Discord.WebSocket.SocketCommandBase.FollowupAsync(String text, Embed[] embeds, Boolean isTTS, Boolean ephemeral, AllowedMentions allowedMentions, MessageComponent components, Embed embed, RequestOptions options)
   at CompanionBot.InteractionHandler.CommandExecuted(ICommandInfo info, IInteractionContext bla, IResult result) in C:\Users\[...]\InteractionHandler.cs:line 97
   at Discord.EventExtensions.InvokeAsync[T1,T2,T3](AsyncEvent`1 eventHandler, T1 arg1, T2 arg2, T3 arg3)
   at Discord.Interactions.CommandInfo`1.ExecuteInternalAsync(IInteractionContext context, Object[] args, IServiceProvider services)
2021-12-29 19:53:21 CommandExec Debug    CommandExecuted Handler called.
2021-12-29 19:53:21 help        Warning  Interaction error in guild Testserver Webhook (781826303128371241): The server responded with error 10015: Unknown Webhook
```
As you can see, the Time that passed from receiving the Dispatch to throwing the Exception is less than a second and not more than three.

**Comment by CottageDwellingCat** [comment]
Can you make sure your system's clock is in sync, then try it again.

**Comment by MaxEtMoritz** [comment]
Re-Syncing the clock solved it, thanks!
