### ISSUE TITLE
The server responded with error 50035: Invalid Form Body

### ISSUE THREAD

**Issue by nikita-petko** [RogueException/Discord.Net#2058]
When I attempt to create application slash commands with integer options, I will get the following exception:

```
Error Type: Discord.Net.HttpException
Error Detail: The server responded with error 50035: Invalid Form Body
Inner Exception:
Exception Stack Trace:
   at Discord.Net.Queue.RequestBucket.<SendAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Discord.Net.Queue.RequestQueue.<SendAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Discord.API.DiscordRestApiClient.<SendInternalAsync>d__78.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Discord.API.DiscordRestApiClient.<SendJsonAsync>d__75`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Discord.API.DiscordRestApiClient.<CreateGlobalApplicationCommandAsync>d__148.MoveNext()6
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Discord.Rest.InteractionHelper.<CreateGlobalCommandAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Discord.WebSocket.DiscordSocketClient.<CreateGlobalApplicationCommandAsync>d__122.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at MFDLabs.Grid.Bot.Extensions.DiscordSocketClientExtensions.CreateGlobalApplicationCommand(DiscordSocketClient client, ApplicationCommandProperties properties, RequestOptions options)
   at MFDLabs.Grid.Bot.Registries.CommandRegistry.ParseAndInsertIntoCommandRegistry()
Exception Source: Discord.Net.Rest
Exception TargetSite: Void MoveNext()
Exception Data: System.Collections.ListDictionaryInternal
```

My options are the following:
![image](https://user-images.githubusercontent.com/79342039/151064759-96ac111c-f7d2-4a0b-a781-df00d1b69242.png)
(If I remove the Integer option it doesn't throw anymore)

**Comment by nikita-petko** [comment]
Never mind I found the issue.
I may make a PR that formats the errors into the HttpException message, as it will make debugging easier, as it just saying "Invalid Form Body" doesn't help:
![image](https://user-images.githubusercontent.com/79342039/151072098-1b8cb893-3a5b-4886-861a-85cee374c7b1.png)

**Comment by nikita-petko** [comment]
https://github.com/discord-net/Discord.Net/pull/2059
