### ISSUE TITLE
Context commands unable to respond at request.

### ISSUE THREAD

**Issue by csmir** [RogueException/Discord.Net#2075]
![image](https://user-images.githubusercontent.com/68127614/152312970-8284c184-0e82-4e9b-81ee-45b7c5c50b14.png)

```cs
fail: Discord[0]
      10:09:26 App Command Discord.Net.HttpException: The server responded with error 10015: Unknown Webhook
         at Discord.Net.Queue.RequestBucket.SendAsync(RestRequest request)
         at Discord.Net.Queue.RequestQueue.SendAsync(RestRequest request)
         at Discord.API.DiscordRestApiClient.SendInternalAsync(String method, String endpoint, RestRequest request)
         at Discord.API.DiscordRestApiClient.SendJsonAsync[TResponse](String method, String endpoint, Object payload, BucketId bucketId, ClientBucketType clientBucket, RequestOptions options)
         at Discord.API.DiscordRestApiClient.CreateInteractionFollowupMessageAsync(CreateWebhookMessageParams args, String token, RequestOptions options)
         at Discord.Rest.InteractionHelper.SendFollowupAsync(BaseDiscordClient client, CreateWebhookMessageParams args, String token, IMessageChannel channel, RequestOptions options)
         at Discord.Rest.RestCommandBase.FollowupAsync(String text, Embed[] embeds, Boolean isTTS, Boolean ephemeral, AllowedMentions allowedMentions, MessageComponent components, Embed embed, RequestOptions options)
         at Discord.Rest.RestInteraction.Discord.IDiscordInteraction.FollowupAsync(String text, Embed[] embeds, Boolean isTTS, Boolean ephemeral, AllowedMentions allowedMentions, MessageComponent components, Embed embed, RequestOptions options)
         at Discord.Interactions.InteractionModuleBase`1.FollowupAsync(String text, Embed[] embeds, Boolean isTTS, Boolean ephemeral, AllowedMentions allowedMentions, RequestOptions options, MessageComponent components, Embed embed)
         at Barriot.Interaction.User.CoreModule.UserinfoAsync(RestUser user)
         at Discord.Interactions.Builders.ModuleClassBuilder.<>c__DisplayClass10_0.<<CreateCallback>g__ExecuteCallback|1>d.MoveNext()
```

This issue was discovered in testing in the following environment:

ASP.NET, .NET 6 (Discord.NET 3.2)

**Reproduction:**

Create a module including the command following the `RestInteraction` pattern. Defer or respond to the application with *no* response as a result, Following up after throws the above error. Execution enters and exits successfully, as an error is thrown and any other internal code executes (as tests imply). Getting `IResult` from the execute method also throws the same error.

**Code:**

```cs
    public class CoreModule : InteractionModuleBase<RestInteractionContext>
    {
        ...
        [UserCommand("anything")]
        public async Task AnythingAsync()
        {
            await DeferAsync(false);

            await FollowupAsync("Test response");
        }
```

**Note:**

No further HTTP error data is passed on this error, the `Data` property contains nothing.

**Comment by csmir** [comment]
Additionally, this was discussed by @Cenngo in private, who seems to get the idea this is from the core library and not from the interaction service.

**Comment by csmir** [comment]
Upon investigating source, I have already come across the issue ^^ even included in the reproduction example.

`InteractionModuleBase` has to be `RestInteractionModuleBase`.
