### ISSUE TITLE
[Bug]: message.ModifyAsync cannot set AllowedMentions

### ISSUE THREAD

**Issue by SeidChr** [RogueException/Discord.Net#2104]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

![image](https://user-images.githubusercontent.com/1927076/153755394-043cb234-f6b6-4710-9b7c-54a65d9a1e19.png)
causes
```
       ---> System.InvalidOperationException: This property has no value set.
         at Discord.Optional`1.get_Value()
         at Discord.Rest.MessageHelper.ModifyAsync(UInt64 channelId, UInt64 msgId, BaseDiscordClient client, Action`1 func, 
RequestOptions options)
```

### Version

3.2.0

### Logs

```
fail: SharpCord.Bot[0]
      Error in non-awaited Task
      System.AggregateException: One or more errors occurred. (This property has no value set.)
       ---> System.InvalidOperationException: This property has no value set.
         at Discord.Optional`1.get_Value()
         at Discord.Rest.MessageHelper.ModifyAsync(UInt64 channelId, UInt64 msgId, BaseDiscordClient client, Action`1 func, RequestOptions options)
         at Bot.<>c.<<InitializeButtonHandlers>b__13_1>d.MoveNext() in Bot.cs:line 154
      --- End of stack trace from previous location ---
         at Bot.OnButtonExecutedAsync(SocketMessageComponent component) in Bot.cs:line 186
         --- End of inner exception stack trace ---
```

### Sample

```cs
        this.buttonHandlers["show-welcome-message"]
            = async component
            => await component.Message.ModifyAsync(message => 
            {
                message.Content = GetWelcomeMessage(component.User.Id);
                message.AllowedMentions = new Optional<AllowedMentions>(AllowedMentions.None);
            });
```

**Comment by d4n3436** [comment]
This seems to be an effect of the criss-cross merge that happened some months ago. In Discord.Net Labs the bug [was fixed 2 months ago](https://github.com/Discord-Net-Labs/Discord.Net-Labs/commit/5e158406c6f27a1cd95edc4833f276429ba5f2dc) but this commit wasn't merged into Discord.Net.
