### ISSUE TITLE
[Bug]: Cannot get a response from slash-commands + defer does not work either

### ISSUE THREAD

**Issue by DaNeubi** [RogueException/Discord.Net#2121]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

While creating the bot and adding slash comands to it, I suddenly got the error message that a Webhook is unknown.
I can issue slash commands, and they get registered properly, but the bot can't reply or defer to a slash-command.
I tried adding the bot with more permissions but this did not help. Neither did generating a new token or create a new discord application with a new bot.

The interesting thing is, that this error only occures in my LAN. Some friends of mine, working on the same project don't have any issue at all.

If you want to see the working example or want to see more code, you can check out the repo. Please note that we are currently using the **_next_**-Branch.[https://github.com/Sahnee-DE/sahnee-bot/tree/next](https://github.com/Sahnee-DE/sahnee-bot/tree/next)

### Version

3.3.0

### Logs

```CS
Discord.Net.HttpException: The server responded with error 10015: Unknown Webhook
         at Discord.Net.Queue.RequestBucket.SendAsync(RestRequest request)
         at Discord.Net.Queue.RequestQueue.SendAsync(RestRequest request)
         at Discord.API.DiscordRestApiClient.SendInternalAsync(String method, String endpoint, RestRequest request)
         at Discord.API.DiscordRestApiClient.SendJsonAsync[TResponse](String method, String endpoint, Object payload, BucketId bucketId, ClientBucketType clientBucket, RequestOptions options)
         at Discord.API.DiscordRestApiClient.ModifyInteractionResponseAsync(ModifyInteractionResponseParams args, String interactionToken, RequestOptions options)
         at Discord.Rest.InteractionHelper.ModifyInteractionResponseAsync(BaseDiscordClient client, String token, Action`1 func, RequestOptions options)
         at Discord.WebSocket.SocketInteraction.ModifyOriginalResponseAsync(Action`1 func, RequestOptions options)
         at Discord.WebSocket.SocketInteraction.Discord.IDiscordInteraction.ModifyOriginalResponseAsync(Action`1 func, RequestOptions options)```

### Sample

This is how I created the slash-command:

```CS
public class TestCommand: InteractionModuleBase<IInteractionContext>
{

    [SlashCommand("test", "Testing")]
    public async Task Test()
    {
        await RespondAsync("Test");
    }
}
```

If I add a try-catch I get the 3 second response error
```CS
System.TimeoutException: Cannot respond to an interaction after 3 seconds!
   at Discord.WebSocket.SocketCommandBase.RespondAsync(String text, Embed[] embeds, Boolean isTTS, Boolean ephemeral, AllowedMentions allowedMentions, MessageComponent components, Embed embed, RequestOptions options)
   at Discord.WebSocket.SocketInteraction.Discord.IDiscordInteraction.RespondAsync(String text, Embed[] embeds, Boolean isTTS, Boolean ephemeral, AllowedMentions allowedMentions, MessageComponent components, Embed embed, RequestOptions options)
   at Discord.Interactions.InteractionModuleBase`1.RespondAsync(String text, Embed[] embeds, Boolean isTTS, Boolean ephemeral, AllowedMentions allowedMentions, RequestOptions options, MessageComponent components, Embed embed)
   at SahneeBot.Commands.TestCommand.Test() in R:\Projects\CS\sahnee-bot\SahneeBot\Commands\TestCommand.cs:line 14

```

**Comment by DaNeubi** [comment]
Well... without anything changed the bot suddenly worked.... Idk

**Comment by Cenngo** [comment]
you sys clock was probably out of sync.

**Comment by DaNeubi** [comment]
my clock wasn't out of sync.
I don't know what happens to me.
Errors keep floating in.
