### ISSUE TITLE
[Bug]: 50035 NUMBER_TYPE_COERCE Error

### ISSUE THREAD

**Issue by bman46** [RogueException/Discord.Net#2163]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

Discord throws an invalid form body 50035 error when a file is uploaded in response to a text command (using `SendFileAsync()` method. 
Appears to work fine with slash commands when using `FollowupWithFileAsync()`

### Version

3.4.0

### Working Version

3.3.2

### Logs

Debugger:
<img width="1127" alt="Screen Shot 2022-03-03 at 12 43 54 AM" src="https://user-images.githubusercontent.com/10489031/156504076-78c2d95f-6f20-4f34-9918-0f56668e7c20.png">

Stack Trace:
```
 ---> Discord.Net.HttpException: The server responded with error 50035: Invalid Form Body
Inner Errors:
NUMBER_TYPE_COERCE: Value "{'Value': 0, 'IsSpecified': True}" is not long.
   at Discord.Net.Queue.RequestBucket.SendAsync(RestRequest request)
   at Discord.Net.Queue.RequestQueue.SendAsync(RestRequest request)
   at Discord.API.DiscordRestApiClient.SendInternalAsync(String method, String endpoint, RestRequest request)
   at Discord.API.DiscordRestApiClient.SendMultipartAsync[TResponse](String method, String endpoint, IReadOnlyDictionary`2 multipartArgs, BucketId bucketId, ClientBucketType clientBucket, RequestOptions options)
   at Discord.API.DiscordRestApiClient.UploadFileAsync(UInt64 channelId, UploadFileParams args, RequestOptions options)
   at Discord.Rest.ChannelHelper.SendFilesAsync(IMessageChannel channel, BaseDiscordClient client, IEnumerable`1 attachments, String text, Boolean isTTS, Embed embed, AllowedMentions allowedMentions, MessageReference messageReference, MessageComponent components, ISticker[] stickers, RequestOptions options, Embed[] embeds, MessageFlags flags)
   at Discord.WebSocket.SocketTextChannel.Discord.IMessageChannel.SendFileAsync(FileAttachment attachment, String text, Boolean isTTS, Embed embed, RequestOptions options, AllowedMentions allowedMentions, MessageReference messageReference, MessageComponent components, ISticker[] stickers, Embed[] embeds, MessageFlags flags)
   at Instagram_Reels_Bot.Modules.TextCommands.Responder(String url, ICommandContext context) in /Users/brendanmcshane/Projects/InstagramEmbedDiscordBot/Instagram Reels Bot/Modules/TextCommands.cs:line 143
   at Instagram_Reels_Bot.Modules.TextCommands.ReelParser(String args) in /Users/brendanmcshane/Projects/InstagramEmbedDiscordBot/Instagram Reels Bot/Modules/TextCommands.cs:line 21
   at Discord.Commands.ModuleClassBuilder.<>c__DisplayClass6_0.<<BuildCommand>g__ExecuteCallback|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Discord.Commands.CommandInfo.ExecuteInternalAsync(ICommandContext context, Object[] args, IServiceProvider services)
   --- End of inner exception stack trace ---
```

### Sample

```
// Create stream from byte array (response.stream)
using (Stream stream = new MemoryStream(response.stream))
{
    // Upload video:
    await context.Message.Channel.SendFileAsync(stream, "video.mp4");
    /** 
     * Above line throws 50035 error.
     * **/
}
```
I have also checked to see if the stream is invalid but when saving it as a file, it plays as expected.

**Comment by unwell35** [comment]
same issue
