### ISSUE TITLE
401 Unauthorized after connected

### ISSUE THREAD

**Issue by fernandesdiego** [RogueException/Discord.Net#2176]
I am trying to upgrade my bot from Discord.net 2.4.0 to 3.4.0. Now all actions from my bot will return an 401 Unauthorized exception.

This how I had it setup.
```C#
        public static async Task Main(string[] args)
        {
            var builder = Host.CreateDefaultBuilder()
                    .ConfigureAppConfiguration(x => x
                        .SetBasePath(GetBasePath())
                        .Build())
                    .ConfigureLogging(x => x
                        .AddConsole()
                        .SetMinimumLevel(LogLevel.Debug))
                    .ConfigureServices((context, services) =>
                    {
                        var connectionString = context.Configuration.GetConnectionString("DefaultConnectionString");
                        var serverversion = ServerVersion.AutoDetect(connectionString);

                        services.AddDbContext<ApplicationContext>(options => { options.UseMySql(connectionString, serverversion); }, ServiceLifetime.Singleton);
                        services.AddSingleton<LavaNode>();
                        services.AddSingleton<LavaConfig>();
                        services.AddSingleton<AudioService>();
                        services.AddSingleton<SteamService>();
                        services.AddHostedService<CommandHandler>();
                        services.AddLavaNode(x =>
                        {
                            x.SelfDeaf = false;
                            x.LogSeverity = LogSeverity.Debug;
                        });
                    })
                    .ConfigureDiscordHost((context, config) =>
                    {
                        config.SocketConfig = new DiscordSocketConfig
                        {
                            LogLevel = LogSeverity.Debug,
                            AlwaysDownloadUsers = true,
                            MessageCacheSize = 200,
                            GatewayIntents = GatewayIntents.All,
                        };
                        config.Token = context.Configuration["Token"];
                    })
                    .UseCommandService((context, config) =>
                    {
                        config.CaseSensitiveCommands = false;
                        config.LogLevel = LogSeverity.Debug;
                        config.DefaultRunMode = RunMode.Sync;
                    })
                .UseConsoleLifetime();

            var host = builder.Build();
            using (host)
            {
                await host.RunAsync();
            }
        }
```

This is what I get on my console
```Console
info: Discord.Addons.Hosting.DiscordHostedService[0]
      Discord.NET hosted service is starting
info: Discord.WebSocket.DiscordSocketClient[0]
      Discord: Discord.Net v3.4.0 (API v9)
dbug: Discord.Addons.Hosting.CommandServiceRegistrationHost[0]
      Registered logger for CommandService
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\Diego\source\repos\fernandesdiego\Bota\Bota\bin\Debug\net5.0
dbug: Microsoft.Extensions.Hosting.Internal.Host[2]
      Hosting started
info: Discord.WebSocket.DiscordSocketClient[0]
      Gateway: Connecting
dbug: Discord.WebSocket.DiscordSocketClient[0]
      Rest: GET gateway: 252,26 ms
warn: Discord.WebSocket.DiscordSocketClient[0]
      Gateway: You're using the GuildScheduledEvents gateway intent without listening to any events related to that intent, consider removing the intent from your config.
warn: Discord.WebSocket.DiscordSocketClient[0]
      Gateway: You're using the GuildInvites gateway intent without listening to any events related to that intent, consider removing the intent from your config.
info: Discord.WebSocket.DiscordSocketClient[0]
      Gateway: Connected
dbug: Discord.WebSocket.DiscordSocketClient[0]
      Gateway: Connected to Servidor de Teste
info: Discord.WebSocket.DiscordSocketClient[0]
      Gateway: Ready


###### trying to execute the /ping command #######


fail: Discord.Commands.CommandService[0]
      Command:
      Discord.Commands.CommandException: Error occurred executing "ping" for ?Diego Fernandes?#3566 in Servidor de Teste/geral.
       ---> Discord.Net.HttpException: The server responded with error 401: 401: Unauthorized
         at Discord.Net.Queue.RequestBucket.SendAsync(RestRequest request)
         at Discord.Net.Queue.RequestQueue.SendAsync(RestRequest request)
         at Discord.API.DiscordRestApiClient.SendInternalAsync(String method, String endpoint, RestRequest request)
         at Discord.API.DiscordRestApiClient.SendJsonAsync[TResponse](String method, String endpoint, Object payload, BucketId bucketId, ClientBucketType clientBucket, RequestOptions options)
         at Discord.API.DiscordRestApiClient.CreateMessageAsync(UInt64 channelId, CreateMessageParams args, RequestOptions options)
         at Discord.Rest.ChannelHelper.SendMessageAsync(IMessageChannel channel, BaseDiscordClient client, String text, Boolean isTTS, Embed embed, AllowedMentions allowedMentions, MessageReference messageReference, MessageComponent components, ISticker[] stickers, RequestOptions options, Embed[] embeds, MessageFlags flags)
         at Bota.Modules.General.PingAsync() in C:\Users\Diego\source\repos\fernandesdiego\Bota\Bota\Modules\General.cs:line 32
         at Discord.Commands.ModuleClassBuilder.<>c__DisplayClass6_0.<<BuildCommand>g__ExecuteCallback|0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Discord.Commands.CommandInfo.ExecuteInternalAsync(ICommandContext context, Object[] args, IServiceProvider services)
         --- End of inner exception stack trace ---


```
I Call ```await _service.ExecuteAsync(context, argPos, _provider)``` on my ```MessageReceived``` event, and my command is like this:
```c#
    public class General : ModuleBase<SocketCommandContext>
    {
        ///...
        [Command("ping")]
        [RequireBotPermission(ChannelPermission.SendMessages)]
        public async Task PingAsync()
        {
            await Context.Channel.SendMessageAsync("Pong!");
            //ReplyAsync("Pong"); produces the same error //
        }
      ///...
    }
```

I checked the issues tab on this repo, but they were all related to peolpe using the wrong token, I double checked mine and I believe It wouldn't even connect if it was wrong. I can see my bot online.

**Comment by csmir** [comment]
Have you looked into the now required GatewayIntents yet?

**Comment by fernandesdiego** [comment]
@Rozen4334 I edited my post to the updated version that includes the gateway intents, my bad. But yes I checked all gateway intents on the developer portal

**Comment by fernandesdiego** [comment]
Problem solved. I was using [Discord.Addons.Hosting](https://github.com/Hawxy/Discord.Addons.Hosting/) package and it was broken. I reinstalled and it works now.
