### ISSUE TITLE
[Bug]: Modals don't work anymore after updating to v3.4.1

### ISSUE THREAD

**Issue by Almighty-Shogun** [RogueException/Discord.Net#2198]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

After updating to Discord.NET v3.4.1 modals have suddenly stopped working. I used the exact example from the documentation but it doesn't want to work. I have confirmed for myself it does work on v3.4.0.

Is there something changed in the way we needs to handle modals or it this an bug?

### Version

3.4.1

### Working Version

3.4.0

### Logs

```
16:28:36 Gateway     A ModalSubmitted handler has thrown an unhandled exception.:
System.InvalidOperationException: Cannot respond, update, or defer twice to the same interaction
   at Discord.WebSocket.SocketModal.RespondAsync(String text, Embed[] embeds, Boolean isTTS, Boolean ephemeral, AllowedMentions allowedMentions, MessageComponent components, Embed embed, RequestOptions opti
ons)
   at PaimonBpHunter.DiscordBot.ModalCommandExecuted(ModalCommandInfo arg1, IInteractionContext arg2, IResult arg3) in D:\GitHub - personal\PaimonBpHunter\DiscordBot.cs:line 134
   at Discord.EventExtensions.InvokeAsync[T1,T2,T3](AsyncEvent`1 eventHandler, T1 arg1, T2 arg2, T3 arg3)
   at Discord.Interactions.CommandInfo`1.InvokeEventAndReturn(IInteractionContext context, IResult result)
   at Discord.Interactions.ModalCommandInfo.ExecuteAsync(IInteractionContext context, IServiceProvider services, String[] additionalArgs)
   at Discord.Interactions.InteractionService.ExecuteModalCommandAsync(IInteractionContext context, String input, IServiceProvider services)
   at Discord.Interactions.InteractionService.ExecuteCommandAsync(IInteractionContext context, IServiceProvider services)
   at PaimonBpHunter.Modules.Events.ModalSubmitted.HandleEventAsync(SocketModal socketModal) in D:\GitHub - personal\PaimonBpHunter\Modules\Events\ModalSubmitted.cs:line 27
   at Discord.EventExtensions.InvokeAsync[T](AsyncEvent`1 eventHandler, T arg)
   at Discord.WebSocket.DiscordSocketClient.TimeoutWrap(String name, Func`1 action)
```

### Sample

Used the exact same sample code as https://discordnet.dev/guides/int_basics/modals/intro.html

### Packages

Not applicable

**Comment by Cenngo** [comment]
Known and fixed #2187. Waiting for commit.
