### ISSUE TITLE
[Bug]: "Cannot start an already running client" on `IVoiceChannel.ConnectAsync()`

### ISSUE THREAD

**Issue by shtrophic** [RogueException/Discord.Net#2247]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [x] I double checked that I have the required intents.

### Description

My implementation is subscribing to `DiscordSocketClient.UserVoiceStateUpdated` and is supposed to play a chime when a user connects to a channel. To achieve this, the subscribing method starts a `StartAudio`-Method on a background task via `Task.Run()`, that creates an `IAudioClient` with `IVoiceChannel.ConnectAsync()`, to send the audio-data via a pcm-stream.

When I am debugging my application via the VisualStudio debugger, stepping through each line, it performs as expected. But without any breakpoints set, the operation fails with an `ObjectDisposedException` originating from Discord.NET.

I guess this originates from `IVoiceChannel.ConnectAsync()`, since a breakpoint before calling this method is reached

### Version

3.5.0

### Logs

```
[15:52:27 INF] Discord-client: [Gateway] | Connected
[15:52:27 INF] Discord-client: [Gateway] | Ready
[15:52:31 INF] Discord-client: [Audio #1] | Connecting
[15:52:35 ERR] Discord-client: [Audio #1] | null
System.ObjectDisposedException: The semaphore has been disposed.
   at System.Threading.SemaphoreSlim.CheckDispose()
   at System.Threading.SemaphoreSlim.Release(Int32 releaseCount)
   at System.Threading.SemaphoreSlim.Release()
   at Discord.Audio.DiscordVoiceAPIClient.ConnectAsync(String url)
   at Discord.Audio.AudioClient.OnConnectingAsync()
   at Discord.ConnectionManager.ConnectAsync(CancellationTokenSource reconnectCancelToken)
   at Discord.ConnectionManager.<>c__DisplayClass29_0.<<StartAsync>b__0>d.MoveNext()
[15:52:35 FTL] GetClientAsync error!
System.InvalidOperationException: Cannot start an already running client.
   at Discord.ConnectionManager.StartAsync()
   at Discord.Audio.AudioClient.StartAsync(String url, UInt64 userId, String sessionId, String token)
   at Discord.WebSocket.SocketGuild.FinishConnectAudio(String url, String token)
   at Discord.WebSocket.SocketGuild.ConnectAudioAsync(UInt64 channelId, Boolean selfDeaf, Boolean selfMute, Boolean external)
   at Discord.WebSocket.SocketGuild.ConnectAudioAsync(UInt64 channelId, Boolean selfDeaf, Boolean selfMute, Boolean external)
   at Discord.WebSocket.SocketVoiceChannel.ConnectAsync(Boolean selfDeaf, Boolean selfMute, Boolean external)
   at DAB.Discord.AudioClientManager.GetClientAsync(IVoiceChannel target, CancellationToken token) in C:\Users\chris\source\repos\DAB\DAB\Discord\AudioClientManager.cs:line 35
[15:52:35 INF] Discord-client: [Audio #1] | Disconnecting
```

### Sample

See [source for callee](https://github.com/Sir-Photch/DAB/blob/master/DAB/Discord/DiscordCommandService.cs) and [for `GetClientAsync()`](https://github.com/Sir-Photch/DAB/blob/master/DAB/Discord/AudioClientManager.cs#L20)

### Packages

CliWrap 3.4.2,
ClrHeapAllocationAnalyzer 3.0.0,
Microsoft.Extensions.Configuration 6.0.1,
Microsoft.Extensions.Configuration.Json 6.0.0,
Microsoft.Extensions.Hosting 6.0.1,
Microsoft.VisualStudio.Threading 17.1.46,
Microsoft.VisualStudio.Threading.Analyzers 17.1.46,
Serilog 2.10.0,
Serilog.Exceptions 8.1.0,
Serilog.Sinks.Async 1.5.0,
Serilog.Sinks.Consolle 4.0.1,
Serilog.Sinks.File 5.0.0,
TagLibSharp 2.2.0

**Comment by shtrophic** [comment]
Weirdly enough, this error does not occur when `ClientUserVoiceStateUpdatedAsync` is triggered by anything else but the client connecting to the discord-server, e.g. muting / unmuting.

**Comment by shtrophic** [comment]
Alright, I got a hacky fix.
Via `await Task.Delay(500)` in the StartAudio-Method ([see here](https://github.com/Sir-Photch/DAB/blob/0560fb15d700f83e54a65918da969a5ad8a246a3/DAB/Discord/DiscordCommandService.cs#L105)) called by `ClientUserVoiceStateUpdated, it works without breakpoints.

I can't imagine this being the way it's supposed to work though??

It seems like the state of `DiscordSocketClient` depends on the completion of invocation of `ClientUserVoiceStateUpdated`, and calling code that modifies that instance causes troubles?

**Comment by csmir** [comment]
Unfortunately the community remains to have a lack of experienced audio contributors, so internal fixes to these issues will take longer than desired. I'm glad you were able to resolve this in a hacky way for now
