### ISSUE TITLE
[Bug]: `SocketInteraction.User` is null when bot doesn't have `bot` scope

### ISSUE THREAD

**Issue by d4n3436** [RogueException/Discord.Net#2259]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

Interactions received through the gateway don't have the `User` property set when a bot is used in a guild and doesn't have the `bot` scope. This causes all uses of `User` to throw a `NullReferenceException` because the property isn't set.

I mentioned this on [a related PR](https://github.com/discord-net/Discord.Net/pull/2217) but it was ignored so I decided to create this issue because I don't know how to fix this bug (and make a PR).
What I know is that the user/member data can be populated because Discord provides the required data.

### Version

3.5.0

### Working Version

None

### Logs

None

### Sample

```cs
var client = new DiscordSocketClient();
client.InteractionCreated += HandleInteractionAsync;

await client.LoginAsync(TokenType.Bot, "token");
await client.StartAsync();

await Task.Delay(Timeout.Infinite);

public async Task HandleInteractionAsync(SocketInteraction interaction)
{
    var user = interaction.User; // Returns null when received from a guild without the "bot" scope
}
```

### Packages

None

**Comment by quinchs** [comment]
This proposed fix in #2271 will only get the global user data out of the member, this means there's no way to check whether the interaction was in a guild or not.

With v4 this will change as our restrictions on creating entities only takes in ids. This fix is the most we can do atm without ripping apart our entire entity structure *again*.

**Comment by d4n3436** [comment]
@quinchs I updated to 3.6.1 and I'm now getting a `NullReferenceException` in pretty much any slash command that has a user parameter.

Stack trace:
```
Gateway: Error handling Dispatch (INTERACTION_CREATE)
System.NullReferenceException: Object reference not set to an instance of an object.
   at Discord.WebSocket.SocketResolvableData`1..ctor(DiscordSocketClient discord, Nullable`1 guildId, T model)
   at Discord.WebSocket.SocketCommandBaseData`1..ctor(DiscordSocketClient client, ApplicationCommandInteractionData model, Nullable`1 guildId)
   at Discord.WebSocket.SocketCommandBaseData..ctor(DiscordSocketClient client, ApplicationCommandInteractionData model, Nullable`1 guildId)
   at Discord.WebSocket.SocketCommandBaseData`1.Create(DiscordSocketClient client, ApplicationCommandInteractionData model, UInt64 id, Nullable`1 guildId)
   at Discord.WebSocket.SocketCommandBase..ctor(DiscordSocketClient client, Interaction model, ISocketMessageChannel channel, SocketUser user)
   at Discord.WebSocket.SocketMessageCommand..ctor(DiscordSocketClient client, Interaction model, ISocketMessageChannel channel, SocketUser user)
   at Discord.WebSocket.SocketMessageCommand.Create(DiscordSocketClient client, Interaction model, ISocketMessageChannel channel, SocketUser user)
   at Discord.WebSocket.SocketInteraction.Create(DiscordSocketClient client, Interaction model, ISocketMessageChannel channel, SocketUser user)
   at Discord.WebSocket.DiscordSocketClient.ProcessMessageAsync(GatewayOpCode opCode, Nullable`1 seq, String type, Object payload)
```

**Comment by d4n3436** [comment]
@quinchs Interactions are still broken on version 3.7.0, specifically message commands and component interactions.

Message command interaction stack trace:
```
Gateway: Error handling Dispatch (INTERACTION_CREATE)
System.NullReferenceException: Object reference not set to an instance of an object.
   at Discord.WebSocket.SocketResolvableData`1..ctor(DiscordSocketClient discord, Nullable`1 guildId, T model)
   at Discord.WebSocket.SocketCommandBaseData`1..ctor(DiscordSocketClient client, ApplicationCommandInteractionData model, Nullable`1 guildId)
   at Discord.WebSocket.SocketCommandBaseData..ctor(DiscordSocketClient client, ApplicationCommandInteractionData model, Nullable`1 guildId)
   at Discord.WebSocket.SocketCommandBaseData`1.Create(DiscordSocketClient client, ApplicationCommandInteractionData model, UInt64 id, Nullable`1 guildId)
   at Discord.WebSocket.SocketCommandBase..ctor(DiscordSocketClient client, Interaction model, ISocketMessageChannel channel, SocketUser user)
   at Discord.WebSocket.SocketMessageCommand..ctor(DiscordSocketClient client, Interaction model, ISocketMessageChannel channel, SocketUser user)
   at Discord.WebSocket.SocketMessageCommand.Create(DiscordSocketClient client, Interaction model, ISocketMessageChannel channel, SocketUser user)
   at Discord.WebSocket.SocketInteraction.Create(DiscordSocketClient client, Interaction model, ISocketMessageChannel channel, SocketUser user)
   at Discord.WebSocket.DiscordSocketClient.ProcessMessageAsync(GatewayOpCode opCode, Nullable`1 seq, String type, Object payload)
   ```
   
Component interaction stack trace:
```
 Gateway: Error handling Dispatch (INTERACTION_CREATE)
System.NullReferenceException: Object reference not set to an instance of an object.
   at Discord.WebSocket.SocketMessageComponent.Update(Interaction model)
   at Discord.WebSocket.SocketMessageComponent.Create(DiscordSocketClient client, Interaction model, ISocketMessageChannel channel, SocketUser user)
   at Discord.WebSocket.SocketInteraction.Create(DiscordSocketClient client, Interaction model, ISocketMessageChannel channel, SocketUser user)
   at Discord.WebSocket.DiscordSocketClient.ProcessMessageAsync(GatewayOpCode opCode, Nullable`1 seq, String type, Object payload)
```
