### ISSUE TITLE
[Bug]: NullReferenceException when registering guild commands

### ISSUE THREAD

**Issue by jnsn** [RogueException/Discord.Net#2268]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

After upgrading Discord.Net to 3.6.0 a `NullReferenceException` is thrown when trying to register guild commands in my ready handler. When I downgrade back to 3.5.0 it works just fine.

### Version

3.6.0

### Working Version

3.5.0

### Logs

```
System.InvalidOperationException: Nullable object must have a value.
   at System.Nullable`1.get_Value()
   at Discord.Rest.RestApplicationCommand.Update(ApplicationCommand model)
   at Discord.Rest.RestGuildCommand.Create(BaseDiscordClient client, ApplicationCommand model, UInt64 guildId)
   at Discord.Rest.ClientHelper.<>c__DisplayClass26_0.<BulkOverwriteGuildApplicationCommandAsync>b__0(ApplicationCommand x)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   at System.Collections.Immutable.ImmutableArray.ToImmutableArray[TSource](IEnumerable`1 items)
   at Discord.Rest.ClientHelper.BulkOverwriteGuildApplicationCommandAsync(BaseDiscordClient client, UInt64 guildId, ApplicationCommandProperties[] properties, RequestOptions options)
   at Discord.Interactions.InteractionService.RegisterCommandsToGuildAsync(UInt64 guildId, Boolean deleteMissing)
```

### Packages

Discord.Net v3.6.0

**Comment by quinchs** [comment]
Fixed in https://github.com/discord-net/Discord.Net/pull/2267, Will close when i push a release

**Comment by quinchs** [comment]
https://github.com/discord-net/Discord.Net/releases/tag/3.6.1
