### ISSUE TITLE
[Bug]: Opus Encoder: BadArg

### ISSUE THREAD

**Issue by amphineko** [RogueException/Discord.Net#2275]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

When I was attempting to invoke `IAudioClient.CreatePCMStream`, `OpusEncoder` throws:

```
System.Exception: Opus Error: BadArg
   at Discord.Audio.OpusConverter.CheckError(OpusError error)
   at Discord.Audio.OpusEncoder..ctor(Int32 bitrate, AudioApplication application, Int32 packetLoss)
   at Discord.Audio.Streams.OpusEncodeStream..ctor(AudioStream next, Int32 bitrate, AudioApplication application, Int32 packetLoss)
   at Discord.Audio.AudioClient.CreatePCMStream(AudioApplication application, Nullable`1 bitrate, Int32 bufferMillis, Int32 packetLoss)
   at <my user code>
```

So I tried to call the constructor of `OpusEncoder` directly with:
```
var encoder = new OpusEncoder(96 * 1024, AudioApplication.Mixed, 30);
```

Inside the constructor, I'm finding out that https://github.com/discord-net/Discord.Net/blob/1b64d19c845cb7c612a1c52288c8b44cff605105/src/Discord.Net.WebSocket/Audio/Opus/OpusEncoder.cs#L49 and https://github.com/discord-net/Discord.Net/blob/1b64d19c845cb7c612a1c52288c8b44cff605105/src/Discord.Net.WebSocket/Audio/Opus/OpusEncoder.cs#L53 are properly run, but https://github.com/discord-net/Discord.Net/blob/1b64d19c845cb7c612a1c52288c8b44cff605105/src/Discord.Net.WebSocket/Audio/Opus/OpusEncoder.cs#L50-L52 always throws.

I'm currently using opus 1.3.1 provided by macOS homebrew.

### Version

3.5.0

### Logs

```
System.Exception: Opus Error: BadArg
   at Discord.Audio.OpusConverter.CheckError(OpusError error)
   at Discord.Audio.OpusEncoder..ctor(Int32 bitrate, AudioApplication application, Int32 packetLoss)
   at Discord.Audio.Streams.OpusEncodeStream..ctor(AudioStream next, Int32 bitrate, AudioApplication application, Int32 packetLoss)
   at Discord.Audio.AudioClient.CreatePCMStream(AudioApplication application, Nullable`1 bitrate, Int32 bufferMillis, Int32 packetLoss)
   at <my user code>
```

### Sample

```
var encoder = new OpusEncoder(96 * 1024, AudioApplication.Mixed, 30);
```

### Packages

- `Discord.Net.Interactions` 3.5.0
- `Discord.Net.WebSocket` 3.5.0

**Comment by amphineko** [comment]
I see my installed opus library has a different name `libopus` rather than `opus` attributed in `DllImport`.

Homebrew provides a `libopus.dylib` and I'm symbolic-linking it as `opus.dylib`. Not sure if it's a mismatch.

```
opus.dylib -> /opt/homebrew/lib/libopus.dylib
```

Can someone name me a working version of opus?

**Comment by KaKusaOAO** [comment]
Hi! Are you using M1 or Intel CPU?
I have same issue here and I'm using an Apple M1 MBP

**Comment by amphineko** [comment]
@KaKusaOAO I'm the same here with arm64 macOS.

I'm feeding Opus-encoded packets to `IAudioClient`, so Discord.Net won't try to open Opus encoders.

Creates a stream accepting Opus packets like [this](https://github.com/amphineko/moonshard/blob/6502680ae805b74865e1679d7dbc8741f5e51242/MoonShard.DiscordBot/Services/AudioClients/AudioClientContext.cs#L32) and writes packet payloads like [this](https://github.com/amphineko/moonshard/blob/6502680ae805b74865e1679d7dbc8741f5e51242/MoonShard.DiscordBot/Services/AudioClients/BufferedPacketStream.cs#L143).
