### ISSUE TITLE
[Bug]: InteractionService.ModifySlashCommandPermissionsAsync() - API error 20001

### ISSUE THREAD

**Issue by MaxEtMoritz** [RogueException/Discord.Net#2335]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

InteractionService.ModifySlashCommandPermissionsAsync() fails with API error 20001: Bots cannot use this endpoint.
It seems like Discord.Net tries to execute the endpoint with a bot token instead of a bearer token, like it is needed [since april 27](https://discord.com/developers/docs/change-log#apr-27-2022).

### Version

3.7.1

### Logs

```
2022-05-28 13:11:18 Gateway     Warning  A Ready handler has thrown an unhandled exception. Discord.Net.HttpException: The server responded with error 20001: Bots cannot use this endpoint
   at Discord.Net.Queue.RequestBucket.SendAsync(RestRequest request)
   at Discord.Net.Queue.RequestQueue.SendAsync(RestRequest request)
   at Discord.API.DiscordRestApiClient.SendInternalAsync(String method, String endpoint, RestRequest request)
   at Discord.API.DiscordRestApiClient.SendJsonAsync[TResponse](String method, String endpoint, Object payload, BucketId bucketId, ClientBucketType clientBucket, RequestOptions options)
   at Discord.API.DiscordRestApiClient.ModifyApplicationCommandPermissionsAsync(ModifyGuildApplicationCommandPermissionsParams permissions, UInt64 guildId, UInt64 commandId, RequestOptions options)
   at Discord.Rest.InteractionHelper.ModifyGuildCommandPermissionsAsync(BaseDiscordClient client, UInt64 guildId, UInt64 commandId, ApplicationCommandPermission[] args, RequestOptions options)
   at Discord.Interactions.InteractionService.ModifyApplicationCommandPermissionsAsync[T](T command, IGuild guild, ApplicationCommandPermission[] permissions)
   at Discord.Interactions.InteractionService.ModifySlashCommandPermissionsAsync(SlashCommandInfo command, IGuild guild, ApplicationCommandPermission[] permissions)
   at CompanionBot.InteractionHandler.RegisterManualCommands() in C:\[...]\CompanionBot\InteractionHandler.cs:line 96
   at CompanionBot.InteractionHandler.RegisterSlashCommandsForTestGuild() in C:\[...]\CompanionBot\InteractionHandler.cs:line 78
   at CompanionBot.Program.ClientReady() in C:\[...]\CompanionBot\Program.cs:line 88
   at Discord.EventExtensions.InvokeAsync(AsyncEvent`1 eventHandler)
   at Discord.WebSocket.DiscordSocketClient.TimeoutWrap(String name, Func`1 action)
```

### Sample

assuming interactionService is an instance of InteractionService,
testGuild is an IGuild instance,
testCommand is a SlashCommandInfo instance registered globally or in testGuild:

```cs
interactionService.ModifySlashCommandPermissionsAsync(testCommand, testGuild, new ApplicationCommandPermission(testGuild.EveryoneRole, false));
```

to replicate the deprecated DefaultPermission(false).

### Packages

Fergun.Interactive v1.5.4

**Comment by csmir** [comment]
You're not allowed to change the permissions of commands any longer with perms v2 being introduced. The new permission system only allows user clients to modify the permissions inside the client, from the guild's `Integrations` settings, this is why your method throws. It is no longer supported by bots.

The only way to manage the permissions for commands now is by using the `EnabledInDmAttribute` and `DefaultMemberPermissionAttribute` above the method handlers marked with `SlashCommandAttribute`, `UserCommandAttribute` or `MessageCommandAttribute`. You can also manage permissions per-module or per-group. Keep in mind that these permissions are only able to be set at registering the commands.

**Comment by d4n3436** [comment]
> You're not allowed to change the permissions of commands any longer with perms v2 being introduced. The new permission system only allows user clients to modify the permissions inside the client, from the guild's `Integrations` settings, this is why your method throws. It is no longer supported by bots.

[You can still modify the permissions](https://discord.com/developers/docs/interactions/application-commands#permissions). Now a Bearer token is required instead of a bot token.
