### ISSUE TITLE
DiscordWebhookClient.ModifyMessageAsync: Failed to generate the bucket id

### ISSUE THREAD

**Issue by Jaywd** [RogueException/Discord.Net#2358]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

`DiscordWebhookClient.ModifyMessageAsync` throws exceptions, no matter how I call it.

### Version

3.7.2

### Logs
```
Message=Failed to generate the bucket id for this operation.
Source=Discord.Net.Rest
StackTrace:
at Discord.API.DiscordRestApiClient.CreateBucketId(Expression`1 endpoint)
at Discord.API.DiscordRestApiClient.<>c__DisplayClass245_0.<GetBucketId>b__0(String x)
at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
at Discord.API.DiscordRestApiClient.GetBucketId(String httpMethod, BucketIds ids, Expression`1 endpointExpr, String callingMethod)
at Discord.API.DiscordRestApiClient.SendJsonAsync[TResponse](String method, Expression`1 endpointExpr, Object payload, BucketIds ids, ClientBucketType clientBucket, RequestOptions options, String funcName)
at Discord.API.DiscordRestApiClient.<ModifyWebhookMessageAsync>d__118.MoveNext()
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Discord.Webhook.WebhookClientHelper.<ModifyMessageAsync>d__2.MoveNext()
(own files redacted)
```

### Sample

```cs
SocketTextChannel channel; // Get from somewhere
var hook = await channel.CreateWebhookAsync("test Hook");
using var client = new DiscordWebhookClient(hook);
var id = await client.SendMessageAsync("test sent");
await client.ModifyMessageAsync(id, m => m.Content = "test modified"); // Throws exception
```

### Packages

-

**Comment by apkd** [comment]
Hey guys, I've been getting the same exception after updating to 3.7.0. Rolling back to 3.6.1 restores the functionality.

```
System.InvalidOperationException: Failed to generate the bucket id for this operation.
 ---> System.InvalidOperationException: Unsupported expression
   at Discord.API.DiscordRestApiClient.GetFieldName(Expression expr)
   at Discord.API.DiscordRestApiClient.CreateBucketId(Expression`1 endpoint)
   --- End of inner exception stack trace ---
   at Discord.API.DiscordRestApiClient.CreateBucketId(Expression`1 endpoint)
   at Discord.API.DiscordRestApiClient.<>c__DisplayClass245_0.<GetBucketId>b__0(String x)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Discord.API.DiscordRestApiClient.GetBucketId(String httpMethod, BucketIds ids, Expression`1 endpointExpr, String callingMethod)
   at Discord.API.DiscordRestApiClient.SendJsonAsync[TResponse](String method, Expression`1 endpointExpr, Object payload, BucketIds ids, ClientBucketType clientBucket, Request
Options options, String funcName)
   at Discord.API.DiscordRestApiClient.ModifyWebhookMessageAsync(UInt64 webhookId, UInt64 messageId, ModifyWebhookMessageParams args, RequestOptions options, Nullable`1 thread
Id)
   at Discord.Webhook.WebhookClientHelper.ModifyMessageAsync(DiscordWebhookClient client, UInt64 messageId, Action`1 func, RequestOptions options, Nullable`1 threadId)
```

**Comment by itsHeroYT** [comment]
I think the issue could be right there:
https://github.com/discord-net/Discord.Net/blob/902326d1f368aa880c035472b33fcfd62d6c39d3/src/Discord.Net.Rest/DiscordRestApiClient.cs#L864

There is a "$" instead of a "?" in the expression
![Bild_2022-08-03_143654482](https://user-images.githubusercontent.com/33837102/182609418-75d8469e-3f91-42a9-8ca9-d095f6ad226c.png)
