### ISSUE TITLE
[Bug]: IMessageChannel.ModifyMessageAsync() seem not to work properly

### ISSUE THREAD

**Issue by budgetdevv** [RogueException/Discord.Net#2372]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

I will preface by stating that this might be caused by my inexperience with this library.

With that aside, the `MessageProperties` Func param seem to contain blank members - An attempt to dereference ` x.Embed.Value` results in an exception being thrown ( More details under Logs section )

### Version

3.7.2

### Logs

```
System.InvalidOperationException: This property has no value set.
   at Discord.Optional`1.get_Value()
   at TextCommandFramework.Modules.PublicModule.<>c.<Test>b__0_0(MessageProperties x) in C:\Users\Administrator\Desktop\DNetEmbedEditBug\WeirdBug\Modules\PublicModule.cs:line 31
   at Discord.Rest.MessageHelper.ModifyAsync(UInt64 channelId, UInt64 msgId, BaseDiscordClient client, Action`1 func, RequestOptions options)
```

### Sample

```csharp
public class PublicModule: ModuleBase<SocketCommandContext>
    {
        [Command("test")]
        public async Task Test()
        {
            var EM = new EmbedBuilder();

            const string Test = "Test";
            
            EM.Title = Test;

            EM.Description = Test;
            
            EM.AddField(Test, Test);

            var Channel = Context.Channel;

            var Msg = await Channel.SendMessageAsync(embed: EM.Build());

            Channel.ModifyMessageAsync(Msg.Id, x =>
            {
                var EMBuilder = x.Embed.Value.ToEmbedBuilder();

                EMBuilder.Fields[0].Value = "LOL";

                x.Embed = EMBuilder.Build();
            });
        }
    }
````

### Packages

<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="7.0.0-preview.5.22301.12" />

**Comment by budgetdevv** [comment]
Full project for reference: https://github.com/budgetdevv/DNetEmbedEditBug

**Comment by budgetdevv** [comment]
Apparently, x does NOT contain old data, and is meant for supplying new data
