### ISSUE TITLE
[Bug]: Can't Login Via Rest API (when the same logic previously could)

### ISSUE THREAD

**Issue by QuinnDamerell** [RogueException/Discord.Net#2373]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

I have been using this lib for a while on my server (it's amazing, thanks!) but just a few hours back I started to get this error when I try to log in to my bot. I filled in all of the details below.

Any ideas? Is this a one-off issue or a widespread issue? It looks like something might have changed in the API and now the Json deserialization is broken?      

### Version

3.7.2 (least)

### Working Version

3.7.2 (until about 3 hours ago)

### Logs

```
JsonSerializationException - Error converting value {null} to type 'Discord.PremiumType'. Path 'premium_type', line 1, position 348. -    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at Discord.Net.Converters.OptionalConverter`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
onReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at Discord.API.DiscordRestApiClient.DeserializeJson[T](Stream jsonStream)
   at Discord.API.DiscordRestApiClient.SendAsync[TResponse](String method, String endpoint, BucketId bucketId, ClientBucketType clientBucket, RequestOptions options)
   at Discord.API.DiscordRestApiClient.GetMyUserAsync(RequestOptions options)
   at Discord.Rest.DiscordRestClient.OnLoginAsync(TokenType tokenType, String token)
   at Discord.Rest.BaseDiscordClient.LoginInternalAsync(TokenType tokenType, String token, Boolean validateToken)
   at Discord.Rest.BaseDiscordClient.LoginInternalAsync(TokenType tokenType, String token, Boolean validateToken)
   at Discord.Rest.BaseDiscordClient.LoginAsync(TokenType tokenType, String token, Boolean validateToken)
```

### Sample

```
   m_restClient = new DiscordRestClient();
   await m_restClient.LoginAsync(Discord.TokenType.Bot, botAuthToken, true);
```

### Packages

Discord.Net

**Comment by QuinnDamerell** [comment]
I should also note that the WebSocket client I'm using is able to log in with no issue, so it doesn't appear to be an issue with my credentials.

**Comment by QuinnDamerell** [comment]
As suspected, when I run the Discord.Net project under the debugger I see this is the response from the GetUser API it's trying to hit

![image](https://user-images.githubusercontent.com/7854873/176536226-7b1b6168-4868-4a62-8979-bcdfd0e67f03.png)

The value of `premium_type` is `null`, which seems fine due to the `Optional` class the value is wrapped in, but it seems that maybe the Json parser can't figure out how to make the `Optional` be null?

**Comment by QuinnDamerell** [comment]
Sorry for the live debugging, but I also tried setting `PremiumType` in the User class to be a `PremiumType?` instead of `Optional<PremiumType>` and it fixes the issue. I'm using dotnet 6.0, but I assume the nullable `?` isn't used due to older packages?

**Comment by mattieboy079** [comment]
I can confirm I have the same issue since an hour ago. With the same error and stacktrace

**Comment by Misha-133** [comment]
It's an issue on Discord's side, they are fixing it rn

**Comment by jgoldshlag** [comment]
Was reported on the D.NET discord, and @quinchs said that it was going to be fixed from discord's end

**Comment by mattieboy079** [comment]
I already thought it was, since they pushed an update today.

**Comment by QuinnDamerell** [comment]
Oh wow, @quinchs is a pretty cool name. ;)

Is there a link to the discussion? 

Also, would it make sense to still update this library to handle it? From the API docs the value looks like it can be optional:
https://discord.com/developers/docs/resources/user#user-object-user-structure 

Edit: Oh, I just realized the `?` in the docs might mean the value might not exist in the json at all. And thus then it would be that it either shouldn't exist or it should be a value int value.

**Comment by quinchs** [comment]
its a discord api issue, theres no point on pushing a hotfix when discord will resolve the issue themselves.

**Comment by kamyker** [comment]
> Sorry for the live debugging, but I also tried setting `PremiumType` in the User class to be a `PremiumType?` instead of `Optional<PremiumType>` and it fixes the issue. I'm using dotnet 6.0, but I assume the nullable `?` isn't used due to older packages?

Doesn't matter when it compiles to net standard 2.0, `Optional<PremiumType>?` also fixes it.

**Comment by csmir** [comment]
Appears to be resolved.
