### ISSUE TITLE
[Bug]: "401 Unauthorized" on several REST client methods

### ISSUE THREAD

**Issue by sjyasuosj** [RogueException/Discord.Net#2381]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

Using DiscordRestClient errors for several endpoints with "401 Unauthorized". 

I'm able to successfully log in using bearer token and verified that it pulls my profile data by looking at ` CurrentUser` property. However, as soon as I call any of the API methods to pull any other data, it errors out and gives me "401 Unauthorized". 

So far I've tried:
`GetDMChannelsAsync`, `GetGuildsAsync`, `GetGroupChannelsAsync`, `GetPrivateChannelsAsync` and `GetGuildUserAsync`.

All of those failed.

### Version

3.7.2

### Logs

      An unhandled exception has occurred while executing the request.
      Discord.Net.HttpException: The server responded with error 401: 401: Unauthorized
         at Discord.Net.Queue.RequestBucket.SendAsync(RestRequest request)
         at Discord.Net.Queue.RequestQueue.SendAsync(RestRequest request)
         at Discord.API.DiscordRestApiClient.SendInternalAsync(String method, String endpoint, RestRequest request)
         at Discord.API.DiscordRestApiClient.SendAsync[TResponse](String method, String endpoint, BucketId bucketId, ClientBucketType clientBucket, RequestOptions options)
         at Discord.API.DiscordRestApiClient.GetGuildAsync(UInt64 guildId, Boolean withCounts, RequestOptions options)
         at Discord.Rest.ClientHelper.GetGuildsAsync(BaseDiscordClient client, Boolean withCounts, RequestOptions options)

### Sample

```
await restClient.LoginAsync(TokenType.Bearer, accessToken);
var guilds = await restClient.GetDMChannelsAsync(); <-- fails
```

### Packages

N/A

**Comment by csmir** [comment]
Does this issue persist in the latest source nightly?

**Comment by Misha-133** [comment]
Closing due to lack of followup
