### ISSUE TITLE
[Bug]: Failed to reconnect after disconnect

### ISSUE THREAD

**Issue by realslimsutton** [RogueException/Discord.Net#2411]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

After running for about a 2 days, the bot had disconnected, almost immediately attempted to reconnect for 1 minute and 40 seconds, at which point it permanently gives up and then disconnects.

I have included two examples in the log, one where the client did successfully reconnect (the usual behaviour) and then this issue (first occurance). Unfortunately, this stack trace is all I have.

### Version

3.7.2

### Logs

[20:29:01 WRN] Gateway:
Discord.WebSocket.GatewayReconnectException: Server requested a reconnect
   at Discord.ConnectionManager.<>c__DisplayClass29_0.<<StartAsync>b__0>d.MoveNext()
[20:29:01 INF] Gateway: Disconnecting
[20:29:01 INF] Gateway: Disconnected
[20:29:02 INF] Gateway: Connecting
[20:29:02 INF] Gateway: Resumed previous session
[20:29:02 WRN] Gateway: You're using the GuildPresences intent without listening to the PresenceUpdate event, consider removing the intent from your config.
[20:29:02 WRN] Gateway: You're using the GuildScheduledEvents gateway intent without listening to any events related to that intent, consider removing the intent from your config.
[20:29:02 WRN] Gateway: You're using the GuildInvites gateway intent without listening to any events related to that intent, consider removing the intent from your config.
[20:29:02 INF] Gateway: Connected
[21:39:10 WRN] Gateway:
Discord.WebSocket.GatewayReconnectException: Server missed last heartbeat
   at Discord.ConnectionManager.<>c__DisplayClass29_0.<<StartAsync>b__0>d.MoveNext()
[21:39:10 INF] Gateway: Disconnecting
[21:39:10 INF] Gateway: Disconnected
[21:39:11 INF] Gateway: Connecting
[21:40:51 INF] Gateway: Disconnecting
[21:40:51 INF] Gateway: Disconnected

### Packages

- Discord.Addons.Hosting (5.1.0)

**Comment by realslimsutton** [comment]
Found this issue in the comments of #2126
