### ISSUE TITLE
[Bug]: Slash Command Builder doc throws exception

### ISSUE THREAD

**Issue by Pompeoar** [RogueException/Discord.Net#2450]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

Following the hello world doc [here ](https://github.com/discord-net/Discord.Net/blob/370bdfa3c630152bfcd851c918f5d49ab6a3116d/docs/guides/int_basics/application-commands/slash-commands/responding-to-slash-commands.md)for creating a slash command via dotnet results in an exception being thrown for guildCommand.Build().

FWIW others in that discord are experiencing the same. 

### Version

3.8.0

### Logs

System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Discord.Net.Core
  StackTrace:
   at Discord.ApplicationCommandProperties.set_NameLocalizations(IReadOnlyDictionary`2 value)
   at Discord.SlashCommandBuilder.Build()
   at VRisingBot.Services.CommandHandler.<Client_Ready>d__7.MoveNext() in C:\Dev\VRisingBot\VRisingBot\VRisingBot\Services\CommandHandler.cs:line 84

### Sample

```cs
 public class CommandHandler
    {
        private readonly DiscordSocketClient client;
        private readonly CommandService commands;
        private readonly IServiceProvider services;

        public CommandHandler(DiscordSocketClient client, CommandService commands, IServiceProvider services)
        {
            this.commands = commands;
            this.services = services;
            this.client = client;
        }

        public async Task InstallCommandsAsync()
        {
            client.Ready += Client_Ready;
            client.SlashCommandExecuted += SlashCommandHandler;
        }    

        private async Task SlashCommandHandler(SocketSlashCommand command)
        {
            await command.RespondAsync($"You executed {command.Data.Name}");
        }

        public async Task Client_Ready()
        {
            // Let's build a guild command! We're going to need a guild so lets just put that in a variable.
            var guild = client.GetGuild(1013836369673597091);

            // Next, lets create our slash command builder. This is like the embed builder but for slash commands.
            var guildCommand = new SlashCommandBuilder();
            // Note: Names have to be all lowercase and match the regular expression ^[\w-]{3,32}$
            guildCommand.WithName("first-command");

            // Descriptions can have a max length of 100.
            guildCommand.WithDescription("This is my first guild slash command!");

            // Let's do our global command
            var globalCommand = new SlashCommandBuilder();
            globalCommand.WithName("first-global-command");
            globalCommand.WithDescription("This is my first global slash command");

            try
            {
                
                // Now that we have our builder, we can call the CreateApplicationCommandAsync method to make our slash command.
                await guild.CreateApplicationCommandAsync(guildCommand.Build());

                // With global commands we don't need the guild.
                await client.CreateGlobalApplicationCommandAsync(globalCommand.Build());
                // Using the ready event is a simple implementation for the sake of the example. Suitable for testing and development.
                // For a production bot, it is recommended to only run the CreateGlobalApplicationCommandAsync() once for each command.
            }
            catch (Exception exception)
            {
                // If our command was invalid, we should catch an ApplicationCommandException. This exception contains the path of the error as well as the error message. You can serialize the Error field in the exception to get a visual of where your error is.
                var json = JsonConvert.SerializeObject(exception.Message, Formatting.Indented);

                // You can send this error somewhere or just print it to the console, for this example we're just going to print it.
                Console.WriteLine(json);
            }
        }
    }
```

### Packages

Azure.Identity
Azure.REsourceManager
Azure.ResourceManager.ContainerInstance
Microsoft.Extensions.DepdencyInjection

**Comment by ericwilliamvogel** [comment]
I'm getting this too! Tried switching .net versions as well with no luck.

**Comment by cloud0259** [comment]
I have a same problem

**Comment by MrJoshuaT** [comment]
I had the same issue. Reverting from 3.8.0 to 3.7.2 stopped the object reference exceptions.

**Comment by Pompeoar** [comment]
Rolling back to 3.7.2 solved it for me. Thanks @MrJoshuaT !
