### ISSUE TITLE
Bot keeps getting disconnected

### ISSUE THREAD

**Issue by Kirschi94** [RogueException/Discord.Net#2454]
Hey, I just have a question: Is it normal for my bot to keep getting disconnected by the remotehost forcefully closing the connection every 10 to 30 minutes? Or is there some problem in my code I'd have to figure out?

**Comment by akaJuliaan** [comment]
this:

`Disconnected`
`Disconnecting`
`Connecting`
`Connected`

messages are normal, discord wants a bot to reconnect sometimes

**Comment by Kirschi94** [comment]
That's very good to know, thank you!
I also get the message `an existing connection was forcibly closed by the remote host` though, is it still normal in that context?

**Comment by akaJuliaan** [comment]
no I've actually never had that before

**Comment by Kirschi94** [comment]
Weird. Happened when I upgraded to 3.8.0, before that there were planned reconnects which were obviously normal, but now it's forcefully disconnecting my bot somehow.

**Comment by brianebeling** [comment]
Are you using .NET 7 preview by chance? Can you post the first few lines of the exception?

**Comment by Syzuna** [comment]
to be fair I am seeing a lot of (even sometimes twice in a row after a fresh reconnect)

```
12:42:36 warn: SyzunaPrograms.CIA.DiscordBot.DiscordBotHostedService[0] System.Exception: WebSocket connection was closed  ---> System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.  ---> System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer.  ---> System.Net.Sockets.SocketException (104): Connection reset by peer    --- End of inner exception stack trace ---    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)    at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](TIOAdapter adapter)    at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)    at System.Net.Http.HttpConnection.ReadBufferedAsyncCore(Memory`1 destination)    at System.Net.Http.HttpConnection.RawConnectionStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)    at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)    at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)    at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TResult](Memory`1 payloadBuffer, CancellationToken cancellationToken)    at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TResult](Memory`1 payloadBuffer, CancellationToken cancellationToken)    at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)    at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state) --- End of stack trace from previous location ---    at Discord.Net.WebSockets.DefaultWebSocketClient.RunAsync(CancellationToken cancelToken)    --- End of inner exception stack trace ---    at Discord.ConnectionManager.<>c__DisplayClass29_0.<<StartAsync>b__0>d.MoveNext()
``` 

and 

```
System.Net.Http.HttpRequestException: An error occurred while sending the request.  ---> System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer.  ---> System.Net.Sockets.SocketException (104): Connection reset by peer    --- End of inner exception stack trace ---    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)    at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](TIOAdapter adapter)    at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)    --- End of inner exception stack trace ---    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)    at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)    at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)    at Discord.Net.Rest.DefaultRestClient.SendInternalAsync(HttpRequestMessage request, CancellationToken cancelToken, Boolean headerOnly)    at Discord.Net.Rest.DefaultRestClient.SendAsync(String method, String endpoint, CancellationToken cancelToken, Boolean headerOnly, String reason, IEnumerable`1 requestHeaders)    at Discord.Net.Queue.RestRequest.SendAsync()    at Discord.Net.Queue.RequestBucket.SendAsync(RestRequest request)    at Discord.Net.Queue.RequestQueue.SendAsync(RestRequest request)    at Discord.API.DiscordRestApiClient.SendInternalAsync(String method, String endpoint, RestRequest request)    at Discord.API.DiscordRestApiClient.SendAsync[TResponse](String method, String endpoint, BucketId bucketId, ClientBucketType clientBucket, RequestOptions options)    at Discord.API.DiscordRestApiClient.GetGatewayAsync(RequestOptions options)    at Discord.API.DiscordSocketApiClient.ConnectInternalAsync()    at Discord.API.DiscordSocketApiClient.ConnectInternalAsync()    at Discord.API.DiscordSocketApiClient.ConnectAsync()    at Discord.WebSocket.DiscordSocketClient.OnConnectingAsync()    at Discord.ConnectionManager.ConnectAsync(CancellationTokenSource reconnectCancelToken)    at Discord.ConnectionManager.<>c__DisplayClass29_0.<<StartAsync>b__0>d.MoveNext()
```

for a few days now.

But I am not sure if they are related to Version 3.8.0 but rather some gateway changes by Discord

**Comment by Kirschi94** [comment]
@brianebeling 
I'm using .NET 4.8 atm, is there a preferred version for usage with Discord.NET I could/should migrate to?
These are the first lines of the reoccurring exception:
```
System.Exception: WebSocket connection was closed ---> System.Net.WebSockets.WebSocketException: An internal WebSocket error occurred. Please see the innerException, if present, for more details.  ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
```

**Comment by brianebeling** [comment]
> @brianebeling 
> I'm using .NET 4.8 atm, is there a preferred version for usage with Discord.NET I could/should migrate to?
> These are the first lines of the reoccurring exception:
> ```
> System.Exception: WebSocket connection was closed ---> System.Net.WebSockets.WebSocketException: An internal WebSocket error occurred. Please see the innerException, if present, for more details.  ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
> ```

Hi. We ran into a similar issue recently, and it turns out the reason was that we used .NET 7 preview and some odd/undocumented changes. Your case seems to be entirely different, though.

Generally speaking, the latest stable version is always a safe bet.

**Comment by csmir** [comment]
@brianebeling With .NET 7 released, is there any chance you could confirm it is still an issue by reproducing? If so, please open a new issue, unrelated to this one.

**Comment by csmir** [comment]
@Kirschi94 Discord dropped support for tls1.1 and lower, I'm pretty sure that is what is causing your problems. Please confirm by testing the connection on net5> from the same machine.

**Comment by brianebeling** [comment]
> @brianebeling With .NET 7 released, is there any chance you could confirm it is still an issue by reproducing? If so, please open a new issue, unrelated to this one.

Sadly, we stopped working on the project for the foreseeable future. If we run into a similar issue again, and I don't forget about it, I will let you know.

**Comment by Syzuna** [comment]
My Bot is running on .NET 7 for some time now and the Full release since today.
I still see the odd ` The remote party closed the WebSocket connection without completing the close handshake.` once in a while but it seemed to have toned down...

**Comment by KrisQuack** [comment]
Hi, Can confirm my bot is still experiencing `The remote party closed the WebSocket connection without completing the close handshake` every few hours in .NET 7 with a very stable connection

**Comment by csmir** [comment]
This is all normal behavior. Cloudflare and Discord often hard-close the websocket connection. Discord.NET knows how to handle this issue and reconnects gracefully.
