### ISSUE TITLE
[Bug]: Cannot modify ephemeral slashCommand response

### ISSUE THREAD

**Issue by JKamsker** [RogueException/Discord.Net#2490]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

The server responds with "Discord.Net.HttpException: 'The server responded with error 10008: Unknown Message'" when trying to Modify an ephemeral message. 
Modifying a non-ephemeral message works as usual.

### Version

3.8.1

### Logs

```
Discord.Net.HttpException: The server responded with error 10008: Unknown Message
   at Discord.Net.Queue.RequestBucket.SendAsync(RestRequest request)
   at Discord.Net.Queue.RequestQueue.SendAsync(RestRequest request)
   at Discord.API.DiscordRestApiClient.SendInternalAsync(String method, String endpoint, RestRequest request)
   at Discord.API.DiscordRestApiClient.SendJsonAsync[TResponse](String method, String endpoint, Object payload, BucketId bucketId, ClientBucketType clientBucket, RequestOptions options)
   at Discord.API.DiscordRestApiClient.ModifyMessageAsync(UInt64 channelId, UInt64 messageId, ModifyMessageParams args, RequestOptions options)
   at Discord.Rest.MessageHelper.ModifyAsync(UInt64 channelId, UInt64 msgId, BaseDiscordClient client, Action`1 func, RequestOptions options)
   at Discord.Rest.RestUserMessage.ModifyAsync(Action`1 func, RequestOptions options)
   at CoderDojo.Management.Discord.Modules.LinkShortenerModule.CreateLinkAsync(String id, String link) in Management.Discord\Modules\LinkShortenerModule.cs:line 161
```

### Sample

```csharp
[SlashCommand("create", "creates shortlink")]
public async Task CreateLinkAsync(string id, string link)
{
    if (!await CheckPermissions())
    {
        return;
    }

    await RespondAsync($"Creating {id}!", ephemeral: true);
    var response = await this.Context.Interaction.GetOriginalResponseAsync();
    // Here i do something that takes a minute or two

    // The problem occurs here:
    await response.ModifyAsync(x => x.Content = $"Create complete! Ready at LINK");
}
```

### Packages

```
<PackageReference Include="AutoMapper" Version="12.0.0" />
<PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.0" />
<PackageReference Include="Discord.Net" Version="3.8.1" />
<PackageReference Include="Microsoft.ApplicationInsights.WorkerService" Version="2.21.0" />
<PackageReference Include="Microsoft.Extensions.Hosting" Version="6.0.1" />
<PackageReference Include="Microsoft.Extensions.Http" Version="6.0.0" />

<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="6.0.1" />
<PackageReference Include="MongoDB.Driver" Version="2.17.1" />
```

**Comment by jgoldshlag** [comment]
There is already a ModifyOriginalResponseAsync on the Interaction, maybe try that?

**Comment by JKamsker** [comment]
Oh yes that works 😅
Did not see that.
Maybe ModifyAsync should be relayed to ModifyOriginalResponseAsync 🤔
