### ISSUE TITLE
[Bug]: (3.9.0) Audit Log for thread updates on forum threads

### ISSUE THREAD

**Issue by mcmonkey4eva** [RogueException/Discord.Net#2533]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

I have compiled a personal copy off dev (55280a569e976b327b41985f333c5f631f8d3af2) for forum-channel support. I've noticed that Audit Logs do not support forum channels yet (refer to NRE trace below gotten on a debug build).

Initially I thought it was because `ThreadType` used on line 35 of `ThreadUpdateAuditLogData` does not support Forum threads yet, however from testing it seems like all the other values are also null, so I guess it's just a completely different format for forum threads vs. non-forum threads.

For my own use case I can just cheat for now with some tacked-on null propagation operators, however before 3.9 is actually released that'll need a proper fix, as it completely breaks reading audit logs if there's forum thread data within the log.

It may or may not be relevant that I have entries in my audit logs that have no content - eg `pinned a message`, `created channel overrides`, etc. literally lack data. I believe those go to separate objects though so shouldn't be.

Some forum thread data in the actual audit log has real data, eg an example `made changes to the thread ...` entry has data `01 - Closed the thread`.
I do also see changes to the tags list for a thread show up as `made changes to the thread ...` with no data on Discord client's view of the audit log.

### Version

3.9.0

### Logs

```
Failed to check thread 123 because System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Discord.Rest.ThreadUpdateAuditLogData.Create(BaseDiscordClient discord, AuditLog log, AuditLogEntry entry) in Discord.Net\src\Discord.Net.Rest\Entities\AuditLogs\DataTypes\ThreadUpdateAuditLogData.cs:line 35
   at Discord.Rest.AuditLogHelper.CreateData(BaseDiscordClient discord, AuditLog log, AuditLogEntry entry) in Discord.Net\src\Discord.Net.Rest\Entities\AuditLogs\AuditLogHelper.cs:line 67
   at Discord.Rest.RestAuditLogEntry..ctor(BaseDiscordClient discord, AuditLog fullLog, AuditLogEntry model, IUser user) in Discord.Net\src\Discord.Net.Rest\Entities\AuditLogs\RestAuditLogEntry.cs:line 18
   at Discord.Rest.RestAuditLogEntry.Create(BaseDiscordClient discord, AuditLog fullLog, AuditLogEntry model) in Discord.Net\src\Discord.Net.Rest\Entities\AuditLogs\RestAuditLogEntry.cs:line 30
   at Discord.Rest.GuildHelper.<>c__DisplayClass33_1.<GetAuditLogsAsync>b__2(AuditLogEntry x) in Discord.Net\src\Discord.Net.Rest\Entities\Guilds\GuildHelper.cs:line 620
```

### Packages

N/A

**Comment by csmir** [comment]
@Misha-133 is this still applicable? You are the forum master here
