### ISSUE TITLE
[Bug]: A task is cancelled error after the bot has disconnected

### ISSUE THREAD

**Issue by JoshuaMaitland** [RogueException/Discord.Net#2679]
### Check The Docs
- [x] I double checked the docs and couldn't find any useful information.

### Verify Issue Source
- [x] I verified the issue was caused by Discord.Net.
### Check your intents
- [X] I double checked that I have the required intents.
### Description

I've been updated the latest version of Discord.Net and when I connect the bot, it's working fine. But when I click on disconnect button (bear in mind that I'm doing this on WinForms in C#) and this error came up like this. (see logs)
This issue seems to be doing this on versions that is higher than 3.9

### Version

Version that is higher than 3.9

### Logs

20:15:12 Discord     Discord.Net v3.10.0 (API v10)
20:15:13 Gateway     Connecting
20:15:14 Gateway     Connected
20:15:15 Gateway     Ready
20:15:22 Gateway     System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.ConnectionManager.<>cDisplayClass29_0.<<StartAsync>b0>d.MoveNext()
20:15:22 Gateway     Disconnecting
20:15:22 Gateway     Disconnected

### Packages

Discord.Net.Commands v3.10.0
Discord.Net.Core v3.10.0
Discord.Net.Interactions v3.10.0
Discord.Net.Rest v3.10.0
Discord.Net.Webhook v3.10.0
Discord.Net.WebSocket v3.10.0
MySql.Data v6.10.9
Newtonsoft.Json v13.0.3

**Comment by JoshuaMaitland** [comment]
Still the same issue after upgrading to v3.11.0
![DiscordNet311TestConsole_2023-07-05_20-38-50](https://github.com/discord-net/Discord.Net/assets/46503276/62c1ee83-cf1d-4b00-b029-9e084ad243c3)

**Comment by Misha-133** [comment]
Idk if this will ever get fixed (at least until v4)
Just to give some backstory:
https://github.com/discord-net/Discord.Net/blob/dev/src/Discord.Net.WebSocket/ConnectionManager.cs#L81-L89

- https://github.com/discord-net/Discord.Net/pull/1580
- https://github.com/discord-net/Discord.Net/pull/1873
- https://github.com/discord-net/Discord.Net/issues/2026
- https://github.com/discord-net/Discord.Net/pull/2030
- https://github.com/discord-net/Discord.Net/pull/2600

**Comment by JoshuaMaitland** [comment]
> Idk if this will ever get fixed (at least until v4) Just to give some backstory: https://github.com/discord-net/Discord.Net/blob/dev/src/Discord.Net.WebSocket/ConnectionManager.cs#L81-L89
> 
> * [fix: Possible fix to one cause of the "connection deadlock" #1580](https://github.com/discord-net/Discord.Net/pull/1580)
> * [fix: "Deadlock" in connecting logic #1873](https://github.com/discord-net/Discord.Net/pull/1873)
> * [v3.1.0 logging a `TaskCanceledException` out of users control #2026](https://github.com/discord-net/Discord.Net/issues/2026)
> * [Add catch for operation canceled in connection manager #2030](https://github.com/discord-net/Discord.Net/pull/2030)
> * [Fix gateway deadlock #2600](https://github.com/discord-net/Discord.Net/pull/2600)

Right, I think that might be the reason why though. Because when I was using v3.9 it doesn't print the TaskCanceledException error whilst with v3.10 or later, it does printed out a error.

**Comment by JoshuaMaitland** [comment]
Still the same issue on v3.13.0

![DiscordNetTestConsole_2024-01-06_12-34-28](https://github.com/discord-net/Discord.Net/assets/46503276/d2c2f35f-b03d-4ef1-8e82-b57425094e3f)

**Comment by JoshuaMaitland** [comment]
One year since I've opened this issue, but it's still hasn't fixed. Still happened on v3.15.0 (latest, at the time of writing to this comment)

![DiscordNetTestConsole_2024-05-15_20-34-13](https://github.com/discord-net/Discord.Net/assets/46503276/68cf8f21-ce92-4f7c-b70e-b306c59d5572)

**Comment by Quantam-Studios** [comment]
> Idk if this will ever get fixed (at least until v4) Just to give some backstory: https://github.com/discord-net/Discord.Net/blob/dev/src/Discord.Net.WebSocket/ConnectionManager.cs#L81-L89
> 
> * [fix: Possible fix to one cause of the "connection deadlock" #1580](https://github.com/discord-net/Discord.Net/pull/1580)
> * [fix: "Deadlock" in connecting logic #1873](https://github.com/discord-net/Discord.Net/pull/1873)
> * [v3.1.0 logging a `TaskCanceledException` out of users control #2026](https://github.com/discord-net/Discord.Net/issues/2026)
> * [Add catch for operation canceled in connection manager #2030](https://github.com/discord-net/Discord.Net/pull/2030)
> * [Fix gateway deadlock #2600](https://github.com/discord-net/Discord.Net/pull/2600)

v4 still is not out.

**Comment by JoshuaMaitland** [comment]
> > Idk if this will ever get fixed (at least until v4) Just to give some backstory: https://github.com/discord-net/Discord.Net/blob/dev/src/Discord.Net.WebSocket/ConnectionManager.cs#L81-L89
> > 
> > * [fix: Possible fix to one cause of the "connection deadlock" #1580](https://github.com/discord-net/Discord.Net/pull/1580)
> > * [fix: "Deadlock" in connecting logic #1873](https://github.com/discord-net/Discord.Net/pull/1873)
> > * [v3.1.0 logging a `TaskCanceledException` out of users control #2026](https://github.com/discord-net/Discord.Net/issues/2026)
> > * [Add catch for operation canceled in connection manager #2030](https://github.com/discord-net/Discord.Net/pull/2030)
> > * [Fix gateway deadlock #2600](https://github.com/discord-net/Discord.Net/pull/2600)
> 
> v4 still is not out.

Exactly. I'm not too sure about v4. I'm way concerned about this. Maybe it could be the change of .NET Framework or something.
