### ISSUE TITLE
[Bug]: Sending a message with a SelectMenu yields a ArgumentNullException

### ISSUE THREAD

**Issue by Nekonika** [RogueException/Discord.Net#2802]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

When trying to send a SelectBox-Component using the following piece of code, a `ArgumentNullException` is being thrown.
This only occurs in the latest version of Discord.Net (3.13.0) - since the parameter `defaultValues` has been added.

I've done a bit of digging into the sourcecode of Discord.Net and identified the issue:

Creating the `SelectMenu` using the `ComponentBuilder` with the following overload of the `WithSelectMenu`-Method and not defining a value for the parameter `defaultValues` causes them to have a value of `null`:
```cs
public ComponentBuilder WithSelectMenu(string customId, List<SelectMenuOptionBuilder> options = null, string placeholder = null, int minValues = 1, int maxValues = 1, bool disabled = false, int row = 0, ComponentType type = ComponentType.SelectMenu, ChannelType[] channelTypes = null, SelectMenuDefaultValue[] defaultValues = null)
{
    return WithSelectMenu(new SelectMenuBuilder().WithCustomId(customId).WithOptions(options).WithPlaceholder(placeholder)
        .WithMaxValues(maxValues)
        .WithMinValues(minValues)
        .WithDisabled(disabled)
        .WithType(type)
        .WithChannelTypes(channelTypes)
        .WithDefaultValues(defaultValues), row);
}
```

This ends up in calling the method `WithDefaultValues` in `SelectMenuBuilder` which has the following structure:
```cs
public SelectMenuBuilder WithDefaultValues(params SelectMenuDefaultValue[] defaultValues)
{
    DefaultValues = defaultValues.ToList();
    return this;
}
```
where `defaultValues` would still have a value of `null` and thus triggering the `ArgumentNullException`, as Linqs `ToList` Method does a null-check on the source parameter.

I'd be creating a PR on this myself, but to be honest, I don't really have enought trust in myself to do this right. :)
As of now, I just pass `Array.Empty<SelectMenuDefaultValue>()` instead of `null`.

### Version

3.13.0

### Working Version

3.12.0

### Logs

```shell
[23.11.23-00:46:33.87] [CRITICAL] [App Commands] Value cannot be null. (Parameter 'source'):
Source: System.Linq
StackTrace:
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Discord.SelectMenuBuilder.WithDefaultValues(SelectMenuDefaultValue[] defaultValues)
   at Discord.ComponentBuilder.WithSelectMenu(String customId, List`1 options, String placeholder, Int32 minValues, Int32 maxValues, Boolean disabled, Int32 row, ComponentType type, ChannelType[] channelTypes, SelectMenuDefaultValue[] defaultValues)
   at RebornLife_ResourceBot.Interactions.TicketSystem_SCMD.Bugreport() in C:\Users\nuk3-\source\repos\RebornLife_ResourceBot\Interactions\TicketSystem_SCMD.cs:line 1180
   at Discord.Interactions.Builders.ModuleClassBuilder.<>c__DisplayClass11_0.<<CreateCallback>g__ExecuteCallback|1>d.MoveNext()
```

### Packages

not relevant

### Environment

not relevant

**Comment by Nekonika** [comment]
Nevermind, I just saw that a PR has been created 18 Hours ago...
https://github.com/discord-net/Discord.Net/pull/2801
