### ISSUE TITLE
When IAudioClient ConnectAsync is created, null is returned

### ISSUE THREAD

**Issue by TABURELTER** [RogueException/Discord.Net#2803]

**Comment by TABURELTER** [comment]
sorry for the code repetition, I suck at writing github questions.

**Comment by Quantam-Studios** [comment]
> I'm trying to broadcast audio via ffmpeg and after I create a connection to a voice channel, IAudioClient is assigned null because of which I can't broadcast audio.
> 
> ```
>public async Task JoinChannel(SocketMessage msg, string URL, IVoiceChannel? channel = null)
>{ 
>     channel ??= (msg.Author as IGuildUser)?.VoiceChannel; 
>     if (channel == null)
>     { 
>         await msg.Channel.SendMessageAsync("Пользователь должен находиться в голосовом канале."); 
>         return;
>     } 
>
>     try
>     { 
>          using (var ffmpeg = CreateStream(URL)) 
>          using (var output = ffmpeg.StandardOutput.BaseStream) 
>          { 
>               AudioOutStream audioClient; audioClient = channel.ConnectAsync(false, false, true).Result.CreatePCMStream(AudioApplication.Music); 
>               try 
>               { 
>                    await output.CopyToAsync(audioClient); 
>               } 
>               finally 
>               { 
>                    await audioClient.FlushAsync(); 
>               }
>          } 
>     } 
>     catch (Exception e) 
>     { 
>          Console.WriteLine(e);
>          throw; 
>     }
>}
>```
> 
> ```
>     private Process CreateStream(string path)
>     {
>         try
>         {
>             return Process.Start(new ProcessStartInfo
>             {
>                 FileName = "ffmpeg/ffmpeg.exe",
>                 Arguments = $"-hide_banner -loglevel panic -i \"{path}\" -ac 2 -f s16le -ar 48000 pipe:1",
>                 UseShellExecute = false,
>                 RedirectStandardOutput = true,
>             });
>         }
>         catch (Exception e)
>         {
>             Console.WriteLine("Process CreateStream");
>             Console.WriteLine(e);
>         }
> 
>         return null;
>     }
> }
> ```

Formatted for the sake of everyone.

**Comment by Quantam-Studios** [comment]
I can't reproduce this.

**Comment by AllahPower** [comment]
The same problem, I have all the code asynchronous, but despite this, a similar error. This problem appeared after some library updates.
`System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Discord.Audio.AudioClient.OnConnectingAsync()
   at Discord.ConnectionManager.ConnectAsync(CancellationTokenSource reconnectCancelToken)
   at Discord.ConnectionManager.<>c__DisplayClass29_0.<<StartAsync>b__0>d.MoveNext()`
