### ISSUE TITLE
[Bug]: Error converting value {null} to type 'System.DateTimeOffset'. Path 'member.joined_at'.

### ISSUE THREAD

**Issue by serkanyazicioglu** [RogueException/Discord.Net#2947]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

While serializing a member data following error is thrown. When I looked at possible places, JoinedAt at Discord.API.Gateway.ExtendedGuild is not nullable and should be changed to nullable.

Serializer Error:
```
Newtonsoft.Json.JsonSerializationException: Error converting value {null} to type 'System.DateTimeOffset'. Path 'member.joined_at'.
---> System.ArgumentException: Could not cast or convert from {null} to System.DateTimeOffset.
at Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(Object value, Type initialType, Type targetType)
at Newtonsoft.Json.Utilities.ConvertUtils.ConvertOrCast(Object initialValue, CultureInfo culture, Type targetType)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
--- End of inner exception stack trace ---
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
```

### Version

3.15.2

### Logs

```shell
Serializer Error:
Newtonsoft.Json.JsonSerializationException: Error converting value {null} to type 'System.DateTimeOffset'. Path 'member.joined_at'.
---> System.ArgumentException: Could not cast or convert from {null} to System.DateTimeOffset.
at Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(Object value, Type initialType, Type targetType)
at Newtonsoft.Json.Utilities.ConvertUtils.ConvertOrCast(Object initialValue, CultureInfo culture, Type targetType)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
--- End of inner exception stack trace ---
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
```

### Packages

N/A

### Environment

OSVersion: Unix 5.15.153.1
Framework: .NETCoreApp,Version=v8.0
OSArchitecture: X64

**Comment by Misha-133** [comment]
> While serializing a member data following error is thrown. When I looked at possible places JoinedAt at Discord.API.Gateway.ExtendedGuild is not nullable and should be changed to nullable.

It is not nullable and the fact it is - is actually a known bug in the API.

**Comment by serkanyazicioglu** [comment]
Hmm, shouldn't it be changed on the ExtendedGuild class to have a workaround till it gets resolved?
On GuildMemberUpdateEvent class it's nullable for example.

**Comment by Misha-133** [comment]
It's a leftover from the times stages could be public

**Comment by Misha-133** [comment]
Right now the only way for it to be `null` - if a user got invited into a VC call as a guest. A staff member confirmed it was a bug. We just gotta wait till they fix this *eventually*

**Comment by serkanyazicioglu** [comment]
Ok then tyvm. Will be closing this then...

**Comment by xXBuilderBXx** [comment]
Actually i've had times when the joined at date is missing in various other circumstances too so making this nullable really should be a fix and backwards patch to allow for lib stability, it's a small change to fix these annoying cases.
