### ISSUE TITLE
ConnectAsync time out

### ISSUE THREAD

**Issue by timmyb4** [RogueException/Discord.Net#2949]
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

When i let mine bot join a voice channel.

the bot times out.

### Version

3.15.2

### Logs

```shell
01:41:16 Discord     Discord.Net v3.15.0 (API v10)
01:41:16 Gateway     Connecting
01:41:17 Gateway     You're using the GuildScheduledEvents gateway intent without listening to any events related to that intent, consider removing the intent from your config.
01:41:17 Gateway     You're using the GuildInvites gateway intent without listening to any events related to that intent, consider removing the intent from your config.
01:41:17 Gateway     Connected
01:41:18 Gateway     Ready
01:41:25 Gateway     A MessageReceived handler is blocking the gateway task.
01:41:37 Gateway     A MessageReceived handler has thrown an unhandled exception.:
System.TimeoutException: The operation has timed out.
   at Discord.WebSocket.SocketGuild.ConnectAudioAsync(UInt64 channelId, Boolean selfDeaf, Boolean selfMute, Boolean external, Boolean disconnect)
   at Discord.WebSocket.SocketGuild.ConnectAudioAsync(UInt64 channelId, Boolean selfDeaf, Boolean selfMute, Boolean external, Boolean disconnect)
   at Program.JoinChannelAsync(SocketCommandContext context) in E:\DiscordBot\TB.TBStudioDiscor.Bot\TB.TBStudioDiscor.Bot\Program.cs:line 91
   at Program.HandleCommandAsync(SocketMessage arg) in E:\DiscordBot\TB.TBStudioDiscor.Bot\TB.TBStudioDiscor.Bot\Program.cs:line 71
   at Discord.EventExtensions.InvokeAsync[T](AsyncEvent`1 eventHandler, T arg)
   at Discord.WebSocket.DiscordSocketClient.TimeoutWrap(String name, Func`1 action)
```

### Sample

```
private async Task JoinChannelAsync(SocketCommandContext context)
{
    var user = context.User as IGuildUser;
    if (user == null || user.VoiceChannel == null)
    {
        await context.Channel.SendMessageAsync("Je moet in een voicekanaal zitten om dit commando te gebruiken.");
        return;
    }

    var voiceChannel = user.VoiceChannel;
    await voiceChannel.ConnectAsync();
}
```

### Packages

YoutubeExplode 6.3.16

### Environment

-**Os**: Windows 11 23H2 22631.3737
-**Architecture**: x64
-**SDK**: .net sdk 8.0.0

**Comment by ZsombocK** [comment]
What did you do that worked, I have the same problem.

**Comment by apache313** [comment]
same problem, what is your solution?
