### ISSUE TITLE
Creating role is broken

### ISSUE THREAD

**Issue by aequasi** [RogueException/Discord.Net#342]
Using either a `SocketGuild`, or a `RestGuild`, with `CreateRoleAsync` both throw the following exception:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Discord.Rest.RoleHelper.<ModifyAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Rest.RestRole.<ModifyAsync>d__40.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Rest.GuildHelper.<CreateRoleAsync>d__16.MoveNext()
```

**Comment by Sentinent** [comment]
The exception occurs on [this part](https://github.com/RogueException/Discord.Net/blob/9fcf88b7acc41c34fc875878282a97e2aeaa5984/src/Discord.Net.Rest/Entities/Roles/RoleHelper.cs#L21) in RoleHelper because `role.Guild` is null. The current `CreateRoleAsync` sends a create role request to the api, then tries to modify the role immediately. However, the guild id is not present in the `Role` object returned from the creation, so the `RestRole.Guild` never gets set anywhere.

**Comment by RXY-R** [comment]
So.... Discord.net is Completely Useless

**Comment by Still34** [comment]
This issue has already been fixed as far as I know, could you elaborate your negative feedback regarding role creation?
