### ISSUE TITLE
400 Bad Request when connecting from cloud service

### ISSUE THREAD

**Issue by judge2020** [RogueException/Discord.Net#370]
I am currently trying to run discord.net through amazon AWS, but as it is not mono compatible (newtonsoft itself isn't) I am resorting to using a windows instance instead of the standard linux instance.

When trying to connect to discord, I am receiving `Error 400 (Bad Request)`, stiming from [SharpRestEngine.cs](https://github.com/RogueException/Discord.Net/blob/master/src/Discord.Net/Net/Rest/SharpRestEngine.cs#L112). There is not much other information that I can retrieve, as it only throws the error code.

I'm not sure what would make this happen, as I can run it on my local machine perfectly fine. I suppose amazon tries to be more strict with http requests in terms of formatting? The AWS help forums as well as google don't give much help.

Thanks for any help.

**Comment by judge2020** [comment]
Also just tried with Microsoft azure, stacktrace: 
```
Unhandled Exception: Discord.Net.HttpException: The server responded with error 400 (BadRequest)
   at Discord.Net.Rest.RestSharpEngine.<Send>d__10.MoveNext() in C:\Users\hunte\Downloads\Discord.Net-master\src\Discord.Net\Net\Rest\SharpRestEngine.cs:line 112
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Net.Rest.RestClient.<Send>d__29.MoveNext() in C:\Users\hunte\Downloads\Discord.Net-master\src\Discord.Net\Net\Rest\RestClient.cs:line 122
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Net.Rest.RestClient.<Send>d__25`1.MoveNext() in C:\Users\hunte\Downloads\Discord.Net-master\src\Discord.Net\Net\Rest\RestClient.cs:line 78
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.DiscordClient.<Login>d__79.MoveNext() in C:\Users\hunte\Downloads\Discord.Net-master\src\Discord.Net\DiscordClient.cs:line 260
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Discord.DiscordClient.<BeginConnect>d__78.MoveNext() in C:\Users\hunte\Downloads\Discord.Net-master\src\Discord.Net\DiscordClient.cs:line 213
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Discord.DiscordClient.<BeginConnect>d__78.MoveNext() in C:\Users\hunte\Downloads\Discord.Net-master\src\Discord.Net\DiscordClient.cs:line 233
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.DiscordClient.<Connect>d__76.MoveNext() in C:\Users\hunte\Downloads\Discord.Net-master\src\Discord.Net\DiscordClient.cs:line 168
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DiscordUpload.Program.<<start>b__2_0>d.MoveNext() in C:\Users\hunte\Documents\Visual Studio 2015\Projects\DiscordUpload\DiscordUpload\Program.cs:line 56
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.DiscordClient.ExecuteAndWait(Func`1 asyncAction) in C:\Users\hunte\Downloads\Discord.Net-master\src\Discord.Net\DiscordClient.cs:line 1063
   at DiscordUpload.Program.start() in C:\Users\hunte\Documents\Visual Studio 2015\Projects\DiscordUpload\DiscordUpload\Program.cs:line 52
   at DiscordUpload.Program.Main(String[] args) in C:\Users\hunte\Documents\Visual Studio 2015\Projects\DiscordUpload\DiscordUpload\Program.cs:line 27
```

**Comment by khionu** [comment]
Are you using a User Account? If so, check your email

**Comment by judge2020** [comment]
Yes, I am using a user account, and that seems to be where the problem is. Testing using a bot account doesn't give the error, however I am fairly certain it is not #349 because I have a discord.net build including the pull request that fixed it.

**Comment by khionu** [comment]
I meant what I said literally. Check your email, the inbox.

**Comment by judge2020** [comment]
Thank you, that didn't even come to mind.
