### ISSUE TITLE
TimeSpan Primitive Type Reader not supported

### ISSUE THREAD

**Issue by james7132** [RogueException/Discord.Net#418]
```
Unhandled Exception: System.InvalidOperationException: System.TimeSpan is not supported as a command parameter, are you missing a TypeReader?
   at Discord.Commands.ModuleClassBuilder.BuildParameter(ParameterBuilder builder, ParameterInfo paramInfo, Int32 position, Int32 count, CommandService service)
   at Discord.Commands.Builders.CommandBuilder.AddParameter(Action`1 createFunc)
   at Discord.Commands.ModuleClassBuilder.BuildCommand(CommandBuilder builder, TypeInfo typeInfo, MethodInfo method, CommandService service)
   at Discord.Commands.Builders.ModuleBuilder.AddCommand(Action`1 createFunc)
   at Discord.Commands.ModuleClassBuilder.BuildModule(ModuleBuilder builder, TypeInfo typeInfo, CommandService service)
   at Discord.Commands.ModuleClassBuilder.<>c__DisplayClass4_0.<BuildSubTypes>b__0(ModuleBuilder module)
   at Discord.Commands.Builders.ModuleBuilder.AddModule(Action`1 createFunc)
   at Discord.Commands.ModuleClassBuilder.BuildSubTypes(ModuleBuilder builder, IEnumerable`1 subTypes, List`1 builtTypes, CommandService service)
   at Discord.Commands.ModuleClassBuilder.Build(IEnumerable`1 validTypes, CommandService service)
   at Discord.Commands.CommandService.<AddModulesAsync>d__18.MoveNext()
```

This is despite there being a default PrimitiveTypeReader for TimeSpan.

**Comment by Auralytical** [comment]
Fixed in https://github.com/RogueException/Discord.Net/commit/b01200f929f18ad9c4f11e2905cd7857c07409d6
