### ISSUE TITLE
ExecuteAsync has an exception occur when an arg is missing.

### ISSUE THREAD

**Issue by natekford** [RogueException/Discord.Net#726]
Stacktrace:
```
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable1 source, Func2 selector)
   at Discord.Commands.CommandService.<ExecuteAsync>g__CalculateScore41_7(CommandMatch match, ParseResult parseResult)
   at Discord.Commands.CommandService.<>c.<ExecuteAsync>b__41_12(KeyValuePair2 x)
   at System.Linq.EnumerableSorter2.ComputeKeys(TElement[] elements, Int32 count)
   at System.Linq.EnumerableSorter1.Sort(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable1.<GetEnumerator>d__1.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator1.MoveNext()
   at System.Linq.Buffer1..ctor(IEnumerable1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable1 source)
   at Discord.Commands.CommandService.<ExecuteAsync>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter1.GetResult()
   at Advobot.Command_Handler.<HandleCommand>d__4.MoveNext() in C:\Users\User\Documents\Visual Studio 2017\Projects\Advobot\Advobot\Advobot_Command_Handler.cs:line 51
```

Command:
```
public async Task Test(string input)
{
	await Actions.SendChannelMessage(Context, "test");
}
```

Input:
```
&&test
```

In the current 1.0.0 version ExecuteAsync produces an exception instead of only failing. In at least `Discord.Net v1.0.0-rc3-00755` this would produce an IResult with IsSuccess = false and an Error/ErrorReason.

**Comment by Joe4evr** [comment]
>`CalculateScore`

#BlameFinite @FiniteReality

**Comment by FiniteReality** [comment]
At least it knows your arg is missing :rofl:
