### ISSUE TITLE
Discord.Net 1.0.1 keeps reconnecting forever

### ISSUE THREAD

**Issue by Erlite** [RogueException/Discord.Net#809]
![image](https://user-images.githubusercontent.com/25248023/30229318-4b1e99b4-94d9-11e7-99a2-932ec0af7628.png)

Keeps doing this in a loop. Let it go for an hour and it doesn't stop. Same after multiple reboots. Attempted to use `WS4NetCore` but it didn't change anything.

Using Debian 8, .Net Core 1.1.1 and Discord.Net 1.0.1

**Comment by FiniteReality** [comment]
Looks like your logging is a bit broken, it's not entirely clear what the problem is here. Could you get back to us with better logs?

**Comment by Erlite** [comment]
![image](https://user-images.githubusercontent.com/25248023/30230281-862c365c-94dd-11e7-97b3-586931dd251f.png)
That's the only thing i can get out of them. Reproduced on Windows 10 too.

```Exception:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.ConnectionManager.<WaitAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.WebSocket.DiscordSocketClient.<OnConnectingAsync>d__93.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Discord.WebSocket.DiscordSocketClient.<OnConnectingAsync>d__93.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.ConnectionManager.<ConnectAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.ConnectionManager.<>c__DisplayClass28_0.<<StartAsync>b__0>d.MoveNext()```

**Comment by FiniteReality** [comment]
Yeah, as I said I think it's either a .NET thing or a cloudflare thing.

**Comment by Erlite** [comment]
Okay so I fixed it, adding `DefaultRetryMode = RetryMode.AlwaysRetry` to the DiscordSocketConfig fixed it. Probably should be added to the quickstart example.
