### ISSUE TITLE
RequireBotPermissionAttribute throws an ArgumentException in a DM context

### ISSUE THREAD

**Issue by Iwuh** [RogueException/Discord.Net#885]
I have a command with the following attributes:
```cs
[Command("damagecalculator")]
[Alias("dc")]
[Summary("Finds the expected raw and element for a weapon based on the input values.")]
[RequireUnlocked]
[RequireBotPermission(ChannelPermission.AddReactions)]
```
In my help command, I check if any commands in the module are usable with
```cs
bool usable = false;
foreach (var command in module.Commands)
{
    var result = await command.CheckPreconditionsAsync(Context, _provider);
    if (result.IsSuccess)
    {
        usable = true;
    }
}
if (!usable) continue;
```
When I run my help command in a guild, it works perfectly fine. In a DM, I get the following stack trace:
```
2017-11-19 15:50:43.4041|ERROR|Command     Discord.Commands.CommandException: Error occurred executing "help" for Iwuh#6351 in @Iwuh#6351. ---> System.ArgumentException: Unknown channel type
Parameter name: channel
   at Discord.ChannelPermissions.All(IChannel channel)
   at Discord.Commands.RequireBotPermissionAttribute.<CheckPermissions>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Commands.CommandInfo.<>c__DisplayClass37_0.<<CheckPreconditionsAsync>g__CheckGroups0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Commands.CommandInfo.<CheckPreconditionsAsync>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at WycademyV2.Commands.Modules.HelpModule.<GetGeneralHelp>d__4.MoveNext() in d:\Documents\Visual Studio 2017\Projects\Git\Wycademy\WycademyV2\src\WycademyV2\Commands\Modules\HelpModule.cs:line 100
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Commands.ModuleClassBuilder.<>c__DisplayClass6_1.<<BuildCommand>g__ExecuteCallback1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Commands.CommandInfo.<ExecuteAsyncInternal>d__41.MoveNext()
   --- End of inner exception stack trace ---
```
I'm not entirely sure why this is but it seems like a [null value is being passed](https://github.com/RogueException/Discord.Net/blob/dev/src/Discord.Net.Commands/Attributes/Preconditions/RequireBotPermissionAttribute.cs#L66) to `ChannelPermissions.All`.

**Comment by AntiTcb** [comment]
Permissions aren't a thing outside of guilds, so this attribute will never work in a DM context. A context check could probably be added within the precondition itself to prevent the exception, but, it shouldn't be used on commands that can be run outside of a guild.

**Comment by khionu** [comment]
I would recommend restricting this command to being in a guild, only, then have a separate command that points to the main command that wraps it with checks for DM.

This is a rather niche area to cover, and it would be complicated to add to the lib. While the exception should be handled correctly, this scenario should be covered by the bot dev.

Ex
```cs
[RequireContext(ContextType.DM | ContextType.Group)]
public async Task CommandInPrivate(string parameter)
    => await CommandInGuild(parameter);

[RequireBotPermission(ChannelPermission.AddReactions), RequireContext(ContextType.Guild)]
public async Task CommandInGuild(string parameter) { ... }
```
