### ISSUE TITLE
MessageReceived problems after idle running in Azure

### ISSUE THREAD

**Issue by cowlike** [RogueException/Discord.Net#904]
Dotnet Core 2.0.3
Linux host on Azure

I have a bot that I've packaged as a Docker container running on Azure Container Instances. I have a very repeatable problem and am currently stuck. After the bot starts, it responds normally to commands I send to it. If I let it sit for about 3 or 4 minutes and send a command, I get no response and see in the log that the gateway is blocked on the MessageHandler. After another minute or so, there is an exception in the log for the task getting canceled and the bot reconnects, after which it is normal again... until I let it sit idle.

It seems like there is a websocket used to POST to Discord's API that is becoming unusable after being idle for some time. Any idea why this is happening and the best way to resolve it quickly? Waiting for 2 minutes until it comes back to life isn't going to work. "Debug" log level output is pasted below. I see events coming in the entire time right up to the "A MessageReceived handler..." message. It's just outbound POSTs that seem to be affected.

<pre>
03:22:55 Gateway     Received Dispatch (TYPING_START)
03:22:57 Gateway     Received Dispatch (CHANNEL_CREATE)
03:22:57 Gateway     Received Dispatch (MESSAGE_CREATE)
03:23:00 Gateway     A MessageReceived handler is blocking the gateway task.
03:23:27 Gateway     Sent Heartbeat
03:24:08 Gateway     System.Exception: Server missed last heartbeat
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.ConnectionManager.<>c__DisplayClass28_0.<<StartAsync>b__0>d.MoveNext()
03:24:08 Gateway     Disconnecting
03:24:08 Gateway     Disconnecting ApiClient
03:24:36 Gateway     A MessageReceived handler has thrown an unhandled exception.:
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Net.Rest.DefaultRestClient.<SendInternalAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Net.Rest.DefaultRestClient.<SendAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Net.Queue.JsonRestRequest.<SendAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Net.Queue.RequestBucket.<SendAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Net.Queue.RequestQueue.<SendAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.API.DiscordRestApiClient.<SendInternalAsync>d__62.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.API.DiscordRestApiClient.<SendJsonAsync>d__59`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.API.DiscordRestApiClient.<CreateMessageAsync>d__77.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Rest.ChannelHelper.<SendMessageAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.EventExtensions.<InvokeAsync>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.WebSocket.DiscordSocketClient.<TimeoutWrap>d__122.MoveNext()
03:24:36 Gateway     Waiting for heartbeater
03:24:36 Gateway     Waiting for guild downloader
03:24:36 Gateway     Clearing large guild queue
03:24:36 Gateway     Raising virtual GuildUnavailables
03:24:36 Gateway     Disconnected from TESTGUILD1
03:24:36 Gateway     Disconnected from TESTGUILD2
03:24:36 Gateway     Disconnected
03:24:37 Gateway     Connecting
03:24:37 Gateway     Connecting ApiClient
03:24:37 Rest        GET gateway: 36.26 ms
03:24:37 Gateway     Received Hello
03:24:37 Gateway     Heartbeat Started
03:24:37 Gateway     Sent Heartbeat
03:24:37 Gateway     Resuming
03:24:37 Gateway     Sent Resume
03:24:37 Gateway     Received HeartbeatAck
03:24:37 Gateway     Latency = 97 ms
03:24:37 Gateway     Received Dispatch (TYPING_START)
03:24:37 Gateway     Received Dispatch (CHANNEL_CREATE)
03:24:37 Gateway     Received Dispatch (MESSAGE_CREATE)
03:24:38 Rest        POST channels/384397718916694016/messages: 108.53 ms
03:24:38 Gateway     Received Dispatch (RESUMED)
03:24:38 Gateway     Sending Status
03:24:38 Gateway     Sent StatusUpdate
03:24:38 Gateway     Connected
03:24:38 Gateway     Raising Event
03:24:38 Gateway     Connected to TESTGUILD1
03:24:38 Gateway     Connected to TESTGUILD2
03:24:38 Gateway     Resumed previous session
03:24:38 Gateway     Received Dispatch (CHANNEL_CREATE)
03:24:38 Gateway     Received Dispatch (MESSAGE_CREATE)
</pre>

**Comment by khionu** [comment]
What that error means is _your_ code is holding up the Gateway. One of your MessageReceived handlers is doing work that is blocking the thread from continuing.

**Comment by cowlike** [comment]
I understand that is what it is supposed to mean but in this case I'm just echoing a string back, like the good old ping/pong example...

<pre>
let now (fmt: string) = System.DateTime.Now.ToString(fmt)

let stampMsg msg = now "MM/dd HH:mm:ss:FFF" + ": " + msg

let sendMsg _ (msg: SocketUserMessage) msgOut =
    msg.Channel.SendMessageAsync(stampMsg msgOut) :> Task
</pre>

Also, I forgot to mention that the running a container locally from the exact same Docker image, on my laptop, doesn't exhibit the problem. There is some network connectivity issue going on here when running in Azure that is extremely slow to recover from. Maybe a good solution would be to expose a way to limit the duration of my self-created tasks rather than letting the library time it out after what seems like a minute or so

[edit: added the stampMsg implementation for completeness... normal response time seems to be around 100ms]

**Comment by khionu** [comment]
If it's hosting provider specific, especially if you're deploying via Docker, this is unlikely an issue with the library. I would recommend adding step-by-step logging to the entirety of your bot. Another option is to try to make as minimal of a bot as possible, and see if you can reproduce. If you can't, slowly readd features until you find the culprit.

**Comment by cowlike** [comment]
Fwiw, I repeated the exact same problem with this demo app:
https://github.com/cowlike/foxbot-example

Looks familiar, right? No docker, just put it on a VM in Azure and ran: ``dotnet run <token>``

This is separate from #883 which I also experience. I'm going to repeat this experiment in AWS as well, just running on a VM without Docker. If that also doesn't work (i.e. has a disconnection problem after 1.5 minutes) then I'll try digging into the library code to see if I can fix it myself. I don't want to keep building on a foundation that doesn't work on a cloud VM.

**Comment by cowlike** [comment]
I have some good news. I deployed the bot on AWS and it's running fine there. This seems to be something odd that is going on with Azure causing the bot to lose connection. I'll look into that separately. 

What do you guys think of letting the user specify a timeout value for their own tasks? The bot would still reconnect but it would be much faster. If there was also an event that the timeout happened, the bot could post a message about something that went wrong. Just some thoughts. I'm gong to bug MS about the Azure problem.

**Comment by nminchow** [comment]
I'm not sure what the policy on closed issues is here, but I am currently seeing very similar behavior when trying to deploy to an Azure VM. @cowlike - did you ever figure out what was happening or did you just stick with aws?

**Comment by javierdlg** [comment]
I can also confirm that I am seeing this issue and I've been seeing it for the past months.
@cowlike have you found any more information regarding this issue? I might be able to find the appropriate person to report this bug to.

**Comment by Cisien** [comment]
For anyone stumbling across this, I recently deployed a bot to azure using Azure Kubernetes Service. 

Try out AKS, ACS, Azure Container Instances, or a linux vm and see if that helps resolve the issue.

**Comment by luizcarlosfaria** [comment]
> For anyone stumbling across this, I recently deployed a bot to azure using Azure Kubernetes Service.
> 
> Try out AKS, ACS, Azure Container Instances, or a linux vm and see if that helps resolve the issue.

5 years later, same problem.

## On Kubernetes
* Lost connections
* Sometimes I can't even establish a connection. 

## On Docker
* Working fine
